name: Check Changed Files

on:
  workflow_call:
    outputs:
      github-changes:
          description: "Changed File output"
          value: ${{ jobs.file-check.outputs.github-changes }}

  workflow_dispatch:

jobs:
  file-check:
    runs-on: self-hosted
    outputs:
      github-changes: ${{steps.check-github-output.outputs.github-changes}}

    name: Check changed files
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Check .github changes
        id: changed-files-github
        uses: tj-actions/changed-files@v39
        with:
          files: |
            .github/**

      - name: Set Output
        id: check-github-output
        run: |
          echo "github-changes=${{steps.changed-files-github.outputs.only_changed}}" >> $GITHUB_OUTPUT