# Get all changed files and check from codeowners and output team names whose approval will be required
---
name: Check Changed Files

on:
  workflow_call:
    inputs:
      changed-files:
        description: 'All the changed files in PR'
        required: true
        type: string
    outputs:
      required-teams:
        description: 'Teams required for approval'
        value: ${{ jobs.read-codeowners.outputs.required-teams }}

  workflow_dispatch:

jobs:
  read-codeowners:
    runs-on: self-hosted
    outputs:
      required-teams: ${{steps.extract-teams.outputs.teams}}
    steps: 
      - name: Extract team names from CODEOWNERS
        id: extract-teams
        run: |
          CHANGED_FILES="${{ inputs.changed-files }}"
          