appGroup: tessell
runner: amd
ci:
  bestPractices:
    jiraValidation:
      jiraIdSource: BRANCH_NAME_PREFIX
      matchingRule: ALL
generates:
  artifacts:
  - buildFunction: dbPluginBuild
    extension: tar.gz
    name: tessell-db-plugin-postgres
    releaseManifestKey: db-plugin-postgres
language: python
tsmInfraVersion: 0.1.83
