#!/bin/bash

function log() {
  echo "${@:-}" >&2
}

function die() { 
  log "${@:-}"
  exit 1
}

function ensure_accessability_to_upload_locations() {
  local deployment_stage
  echo "Generating STS session token..."
  generate_sts_session_token "${AWS_ACCOUNT_TESSELL_COMMON_INFRA}"
  echo "Checking access to upload locations..."
  for deployment_stage in dev qa stage prod; do
    [[ -n $(mc ls ${MC_ALIAS_FOR_CONVOY_MINIO}/tessell-artifacts-${deployment_stage}) ]] || \
      die "Failed to access MinIO bucket: ${MC_ALIAS_FOR_CONVOY_MINIO}/tessell-artifacts-${deployment_stage}"
    
    aws s3api head-bucket --bucket tessell-artifacts-${deployment_stage} &>/dev/null || \
      die "Failed to access S3 bucket 'tessell-artifacts-${deployment_stage}' in common-infra account"
  done
  echo "Access to upload locations verified."
  # TODO: Add check for Nexus access
}
