#!/bin/bash

buildConvoyTessellImage() {
  build_convoy_tessell_image "$@"
}

buildConvoyTessellClient() {
  build_convoy_tessell_client "$@"
}

buildConvoyTessellImageAndPush() {
  build_convoy_tessell_image_and_push "$@"
}

buildConvoyTessellClientAndPush() {
  build_convoy_tessell_client_and_push "$@"
}

configureNpmrc() {
  configure_npmrc "$@"
}

configureNpmrcYarnrc() {
  configure_npmrc_yarnrc "$@"
}

dockerBuild() {
  docker_build "$@"
}

dockerBuildAndPush() {
  docker_build_and_push "$@"
}

gradlewUIBuild() {
  gradlew_ui_build "$@"
}

gradlewUIBuildAndPush() {
  gradlew_ui_build_and_push "$@"
}

mvnDeploy() {
  mvn_deploy "$@"
}

npmBuild() {
  npm_build "$@"
}

npmBuildAndPush() {
  npm_build_and_push "$@"
}

opsUIBuild() {
  ops_ui_build "$@"
}

opsUIBuildAndPush() {
  ops_ui_build_and_push "$@"
}

pushToNexus() {
  push_to_nexus "$@"
}

pythonDockerBuildAndPush() {
  python_docker_build_and_push "$@"
}

qaBuildAndPush(){
  qa_build_and_push "$@"
} 

setupQAEnv() {
  setup_qa_env "$@"
}

tsmZipBuildAndPush() {
  tsm_zip_build_and_push "$@"
}

vssTarBuildAndPush() {
  vss_tar_build_and_push "$@"
}

validateInputs() {
  validate_inputs "$@"
}

zipDirectory() {
  zip_directory "$@"
}
