#!/bin/bash

awsConfigureDevqaInfra() {
  aws_configure_devqa_infra "$@"
}

createTFBackend() {
  create_tf_backend "$@"
}

buildConvoyTessellImage() {
  build_convoy_tessell_image "$@"
}

buildConvoyTessellClient() {
  build_convoy_tessell_client "$@"
}

buildConvoyTessellImageAndPush() {
  build_convoy_tessell_image_and_push "$@"
}

buildConvoyTessellClientAndPush() {
  build_convoy_tessell_client_and_push "$@"
}

dockerBuild() {
  docker_build "$@"
}

dockerBuildAndPush() {
  docker_build_and_push "$@"
}

mvnDeploy() {
  mvn_deploy "$@"
}

pythonDockerBuildAndPush() {
  python_docker_build_and_push "$@"
}

qaBuildAndPush(){
  qa_build_and_push "$@"
} 

setupQAEnv() {
  setup_qa_env "$@"
}

terraformApply() {
  terraform_apply "$@"
}

terraformApplyAndPush() {
  terraform_apply_and_push "$@"
}

tsmZipBuildAndPush() {
  tsm_zip_build_and_push "$@"
}

vssTarBuildAndPush() {
  vss_tar_build_and_push "$@"
}

validateInputs() {
  validate_inputs "$@"
}

zipDirectory() {
  zip_directory "$@"
}
