name: 'Find Latest Tag'

description: 'Find the latest tag'

inputs:
  tags:
    description: 'Space-separated list of tags'
    required: true
  source_branch:
    description: 'Source branch'
    required: true

runs:
  using: 'node12'
  main: 'index.js'

outputs:
  tag_ref:
    description: 'Latest tag reference'

branding:
  icon: 'tag'

permissions:
  actions: read

env:
  CIPIPELINE_NEXUS_PASSWORD: ${{ secrets.CIPIPELINE_NEXUS_PASSWORD }}
