---
name: 'Dispatch build and wait'
description: 'Dispatches the job to build the given repository and wait'
inputs:
  organisation:
    description: 'Tag which got created after merge to release branch'
    required: true
  repo_name:
    description: 'Branch against which PR need to be created'
    required: true
  branch_name:
    description: 'Branch to build.'
    required: true
    default: 'main'
  github-token:
    description: 'Override for github token'
    required: false
    default: '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'
outputs:
  job_status:
    description: 'The PR created.'
runs:
  using: 'node12'
  main: 'index.js'
