#!/usr/bin/env bash

set -Eeuo pipefail

script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

BRANCH=${1:-$(git branch --show-current)}

cd ${script_dir}/../.github
files_to_modify=$(find . -type f | grep '^./ci-scripts/\|^./workflows/')

for i in ${files_to_modify}; do
  sed -i '' "s/@TDEVOPS-4148/@${BRANCH}/;s/CONVOY_API_ENDPOINT/CONVOY_DEV_API_ENDPOINT/;s/CI_BRANCH: TDEVOPS-4148/CI_BRANCH: ${BRANCH}/" ${i}
done
