#!/usr/bin/env bash

set -Eeuo pipefail

script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

if [[ -z ${1:-} ]]; then
  echo "This script expects one single argument: the name of the test branch to create"
  exit 1
fi

cd ${script_dir}/../.github
files_to_modify=$(find . -type f | grep '^./ci-scripts/\|^./workflows/')

for i in ${files_to_modify}; do
  sed -i '' "s/@TDEVOPS-3633_convoy_ci_on_3693_test/@${1}/;s/CONVOY_DEV_API_ENDPOINT/CONVOY_DEV_API_ENDPOINT/;s/CI_BRANCH: TDEVOPS-3633_convoy_ci_on_3693_test/CI_BRANCH: ${1}/" ${i}
done
