#!/usr/bin/env bash

set -Eeuo pipefail

script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

BRANCH=${1:-$(git branch --show-current)}

cd ${script_dir}/../.github
files_to_modify=$(find . -type f | grep '^./ci-scripts/\|^./workflows/')

for i in ${files_to_modify}; do
  sed -i '' "s/@${1}/@main/;s/CONVOY_DEV_API_ENDPOINT/CONVOY_API_ENDPOINT/;s/CI_BRANCH: ${1}/CI_BRANCH: main/" ${i}
done
