# This is a basic workflow to help you get started with Actions
name: Tessell Pipelines Code Build

# Controls when the workflow will run
on:
  workflow_call:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted
    outputs:
      mail_id_output: ${{ steps.mail_info.outputs.mail_id }}
      mail_subject_output: ${{ steps.mail_info.outputs.mail_subject}}
      mail_body_output: ${{ steps.mail_info.outputs.mail_body }}
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL  }}
      NEXUS_SERVER: nexus.tessell.cloud
      NEXUS_PULL_REPOS_PY: tessell-py-development
      GITHUB_USER: ${{ secrets.CIPIPELINE_NEXUS_USERNAME }}
      GITHUB_TOKEN: ${{ secrets.CIPIPELINE_NEXUS_PASSWORD }}
      GROUP_NAME: "tessell.terraform_modules"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"

      - name: Get branch name && repo name 
        shell: bash
        run: |
          pwd
          echo "SOURCE_BRANCH=$(echo ${GITHUB_REF#refs/heads/} | tr / -)" >> $GITHUB_ENV
          echo "REPO_NAME=$(git ls-remote --get-url | xargs basename -s .git)" >> $GITHUB_ENV
          
      - name: finding the modified dir's
        id: modified_dir
        uses: actions/github-script@v6.3.3
        with:
          github-token: ${{ secrets.CIPIPELINE_NEXUS_PASSWORD  }}
          script: |
            head_commit = "${{ github.sha }}"
            base_commit = "${{ github.sha }}"
            if ( "${{ github.event.before }}" != '0000000000000000000000000000000000000000') { 
              base_commit = "${{ github.event.before }}"
            }
            if ( "${{ github.event_name }}" == 'pull_request') {
              console.log("Using the base branch's commit for comparing.")
              base_commit = "${{ github.event.pull_request.base.sha  }}"
            }
            console.log("base_commit " + base_commit);
            console.log("head_commit " + head_commit); 
            response = await github.rest.repos.compareCommits({
                owner: "${{ github.repository_owner }}",
                repo: "${{  github.repository }}".split('/')[1],
                head: head_commit,
                base: base_commit
            });
              const excludedDirectories = ['.github','.gitignore'];
              const modifiedFiles = response.data.files;
              const modifiedDirectories = [];
              response.data.files.forEach(file => {
                const fileDirectory = file.filename.split("/")[0];
                if (!excludedDirectories.includes(fileDirectory)) {
                  modifiedDirectories.push(fileDirectory)
                }
              });
              const uniqueDirectories = [...new Set(modifiedDirectories)];
              const outputString = uniqueDirectories.join(' ');
              core.setOutput('modifiedDirectories', outputString);

      - name: Zip terraform modules
        shell: bash
        run: |
          BASE_DIR=$PWD
          BUILD_DIR=$BASE_DIR/build
          mkdir -p $BUILD_DIR
          DIRECTORIES="${{ steps.modified_dir.outputs.modifiedDirectories }}"
          EXCLUDE_DIR=("build")
          for DIR in $DIRECTORIES
          do
            if [[ " ${EXCLUDE_DIR[*]} " != *"$DIR"* ]]; then 
              echo "building  ${DIR}"
              ARTIFACT_FILE=$BUILD_DIR/${DIR}.zip
              cd $BASE_DIR/$DIR
              VERSION=$(cat version.txt | awk -F "=" {'print $2'})
              echo terraform_build $BASE_DIR/$DIR $ARTIFACT_FILE
              terraform_build $PWD $ARTIFACT_FILE
            fi
          done
          ls -lrta $BUILD_DIR

      - name: Upload terraform modules to nexus
        if: ${{ startsWith(env.SOURCE_BRANCH,'rel-') || env.SOURCE_BRANCH == 'main' }}
        shell: bash
        run: |
          BASE_DIR=$PWD
          BUILD_DIR=$BASE_DIR/build
          mkdir -p $BUILD_DIR
          DIRECTORIES="${{ steps.modified_dir.outputs.modifiedDirectories }}"
          EXCLUDE_DIR=("build")
          for DIR in $DIRECTORIES
          do
            if [[ " ${EXCLUDE_DIR[*]} " != *"$DIR"* ]]; then 
              ARTIFACT_FILE=$BUILD_DIR/${DIR}.zip
              cd $BASE_DIR/$DIR
              VERSION=$(cat version.txt | awk -F "=" {'print $2'})
              echo terraform_build $BASE_DIR/$DIR $ARTIFACT_FILE
              terraform_build $PWD $ARTIFACT_FILE

              mvn deploy:deploy-file -Dnexus_url=https://${NEXUS_SERVER}/repository/tessell-m2-component \
                -Dnexus_username=${GITHUB_USER} -Dnexus_password=${GITHUB_TOKEN} \
                -DgroupId=${GROUP_NAME} -DartifactId=${DIR} -Dversion=$VERSION \
                -DgeneratePom=true -Dpackaging=zip \
                -Durl=https://${NEXUS_SERVER}/repository/tessell-repos-m2-component \
                -Dfile=${ARTIFACT_FILE} -DrepositoryId=nexus

            fi
          done

      - name: Slack Notification
        uses: act10ns/slack@v1.5.0
        if: ${{ failure() && (startsWith(env.SOURCE_BRANCH,'rel-') || env.SOURCE_BRANCH == 'main') }}
        with:
           status: ${{ job.status }}
           steps: ${{ toJson(steps) }}
           channel: ${{ secrets.SLACK_DEVOPS_CHANNEL  }}
      
      - name: Get PR-Author,subject & body to send email
        if: ${{ failure() && contains(github.event.pull_request.head.ref, 'double_commit') }}
        run: |
          echo "MAILID=$(git log -1 '${{ github.event.pull_request.head.sha }}' --pretty=format:'%ae')" >> $GITHUB_ENV
          echo "BODY=JOB_STATUS : ${{ job.status }} %0A WORKFLOW : ${{ github.workflow }} %0A EVENT : ${{ github.event_name }} %0A BRANCH : ${{ env.SOURCE_BRANCH }} %0A COMMIT_ID : ${{ github.sha }} %0A REPO : ${{ github.repository }}" >> $GITHUB_ENV
 
      - name: sending output
        if: ${{ failure() && contains(github.event.pull_request.head.ref, 'double_commit') }}
        id: mail_info
        run: |
          echo "mail_id=${{ env.MAILID }}" >> $GITHUB_OUTPUT
          echo "mail_subject=***${{ job.status }}*** || ${{ github.workflow }}  ||  ${{ github.repository }} " >> $GITHUB_OUTPUT
          echo "mail_body=${{ env.BODY }}" >> $GITHUB_OUTPUT
        
  send-mail:
    uses: ./.github/workflows/email_dc.yaml
    needs: build
    with:
      subject: ${{ needs.build.outputs.mail_subject_output }}
      body: ${{ needs.build.outputs.mail_body_output }} 
      to: ${{ needs.build.outputs.mail_id_output }}
    secrets: inherit
    if: ${{ failure() && contains(github.event.pull_request.head.ref, 'double_commit') }}
