# This is a basic workflow to help you get started with Actions
name: Tessell Pipelines Code Build

# Controls when the workflow will run
on:
  workflow_call:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    outputs:
      mail_id_output: ${{ steps.mail_info.outputs.mail_id }}
      mail_subject_output: ${{ steps.mail_info.outputs.mail_subject}}
      mail_body_output: ${{ steps.mail_info.outputs.mail_body }}
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL  }}
      NEXUS_SERVER: ${{ vars.NEXUS_SERVER_ENDPOINT }}
      GITHUB_TOKEN: ${{secrets.CIPIPELINE_GITHUB_TOKEN}}
      NEXUS_PULL_REPOS_PY: tessell-py-development
      NEXUS_PUSH_REPOS_PY: ${{ vars.NEXUS_PUSH_REPOS_PY }}
      DOCKERHUB_ORG: "tesselldev"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1

      - name: Set up Python
        uses: actions/setup-python@v5.0.0
        with:
          python-version: 3.9       

      - name: Vulnerability scan1
        if: ${{ !startsWith(env.SOURCE_BRANCH,'rel-') && env.SOURCE_BRANCH != 'main' }}
        id: vaulnerability-scan1
        env:
          API_URL: http://${{vars.CONVOY_API_ENDPOINT}}/devops/code-scan/vulnerabilities/validate
          REPO: "${{github.repository}}"
          API_KEY: ${{secrets.CONVOY_AUTH_TOKEN}}
          SLACK_TOKEN: ${{secrets.SLACK_TOKEN}}
          DEVOPS_TEAM: ${{secrets.DEVOPS_TEAM_SLACK_ID}}
          CHANNEL_ID: ${{secrets.CONVOY_ALERTS_SLACK_CHANNEL}}
          trivy_version: ${{ vars.TRIVY_VERSION }}
        run: |
          wget https://github.com/aquasecurity/trivy/releases/download/v0.48.3/trivy_0.48.3_Linux-64bit.deb
          sudo dpkg -i trivy_0.48.3_Linux-64bit.deb
          trivy -v
          trivy -v
          trivy image -f json -o trivy_image_scan_result.json ${{ env.DOCKER_IMAGE_NAME }}:latest
          python3 - <<EOF
          import requests
          import json
          import os
          import time
          import base64
          API_URL = os.environ.get('API_URL')
          API_KEY = os.environ.get('API_KEY')
          REPO = os.environ.get('REPO')
          def post_to_slack(message):
            usergroup_id=os.environ.get('DEVOPS_TEAM')
            mention = f"<!subteam^{usergroup_id}>"
            full_message=f"{mention}\n vulnerability validation failed, please check \n```{message}```"
            client = WebClient(token=os.environ.get('SLACK_TOKEN'))
            try:
              response = client.chat_postMessage(channel=os.environ.get('CHANNEL_ID'), text=full_message)
              return response["ok"]
            except SlackApiError as e:
              print(f"Error posting to Slack: {e.response['error']}")
              return False
          with open('trivy_image_scan_result.json') as user_file:
            parsed_json = json.load(user_file)
          payload = {
            "repoName": REPO,
            "CVE":parsed_json
          }
          headers = {
            'Content-Type': 'application/json',
            'x-api-key': API_KEY
          }
          try:
            response = requests.post(API_URL, json=payload, headers=headers)
            if response.status_code == 200:
              print(response.status_code)
              print(response.text)
            elif response.status_code == 409:
              print(response.json())
              print("Get approval for these vulnerabilities or fix them")
              exit(1)
            else:
              print(response.status_code)
              print(response.text)
              post_to_slack(response.text)
              exit(1)
          except Exception as e:
            post_to_slack(response.text)
              exit(1) 
          EOF

      - name: Set up JDK 17
        uses: actions/setup-java@v4.0.0
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Get branch name & Repo Name
        shell: bash
        run: |
          echo "SOURCE_BRANCH=$(echo ${GITHUB_REF#refs/heads/} | tr / -)" >> $GITHUB_ENV
          echo "REPO_NAME=$(echo ${GITHUB_REPOSITORY} | cut -f2 -d'/')" >> $GITHUB_ENV
          echo "DOCKER_IMAGE_NAME=$(echo ${GITHUB_REPOSITORY} | cut -f2 -d'/')" >> $GITHUB_ENV

      - name: Set Pull repository
        if: ${{ startsWith(env.SOURCE_BRANCH,'rel-') || env.SOURCE_BRANCH == 'main' }}
        shell: bash
        run: |
          echo "NEXUS_PULL_REPOS_PY=tessell-py-component" >> $GITHUB_ENV
          echo "DOCKERHUB_ORG=tessellprod" >> $GITHUB_ENV

      - name: Create pip conf
        run: |
          # Create pip.conf and copy to /etc; 
          # The --extra_index_url option of pip install does not work with username/password
          # Also pip does not have separate option to specify creds.
          echo "[global]" > pip.conf
          echo "index =  https://${{ secrets.CIPIPELINE_NEXUS_USERNAME }}:${{ secrets.CIPIPELINE_NEXUS_PASSWORD }}@${{ env.NEXUS_SERVER }}/repository/${{ env.NEXUS_PULL_REPOS_PY }}/simple" >> pip.conf
          echo "index-url = https://${{ secrets.CIPIPELINE_NEXUS_USERNAME }}:${{ secrets.CIPIPELINE_NEXUS_PASSWORD }}@${{ env.NEXUS_SERVER }}/repository/${{ env.NEXUS_PULL_REPOS_PY }}/simple" >> pip.conf
          echo "extra-index-url = https://pypi.org/simple" >> pip.conf
          sudo cp pip.conf /etc/pip.conf
        shell: bash

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install flake8 pytest twine wheel
          python3 -m pip install -r ${{ env.REPO_NAME }}/requirements.txt --dry-run

      - name: Lint with flake8
        run: |
          export PATH=/opt/tessell/python/install/bin:$PATH
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Test with pytest
        if: false
        run: |
          export PATH=/opt/tessell/python/install/bin:$PATH
          pytest

      - name: Login to docker
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}


      - name: Build Wheel
        if: ${{ !startsWith(env.SOURCE_BRANCH,'rel-') && env.SOURCE_BRANCH != 'main' }}
        run: |
          export PATH=/opt/tessell/python/install/bin:$PATH
          ./gradlew pythonWheel docker --console plain \
            -Pnexus_username="${{ secrets.CIPIPELINE_NEXUS_USERNAME }}" \
            -Pnexus_password="${{ secrets.CIPIPELINE_NEXUS_PASSWORD }}" \
            -Pdockerhub_org="${{ env.DOCKERHUB_ORG }}"


      - name: Build and push
        if: ${{ startsWith(env.SOURCE_BRANCH,'rel-') || env.SOURCE_BRANCH == 'main' }}
        run: |
          export PATH=/opt/tessell/python/install/bin:$PATH
          ./gradlew twineUpload dockerTag --console plain \
            -Pnexus_push_username="${{ secrets.CIPIPELINE_NEXUS_USERNAME }}" \
            -Pnexus_push_password="${{ secrets.CIPIPELINE_NEXUS_PASSWORD }}" \
            -Pnexus_username="${{ secrets.CIPIPELINE_NEXUS_USERNAME }}" \
            -Pnexus_password="${{ secrets.CIPIPELINE_NEXUS_PASSWORD }}" \
            -Pnexus_push_repo_py="${{ env.NEXUS_PUSH_REPOS_PY }}" \
            -Pnexus_pull_repo_py="${{ env.NEXUS_PULL_REPOS_PY }}" \
            -Pdockerhub_org="${{ env.DOCKERHUB_ORG }}"

      - name: getting commit id for workflow_dispatch
        uses: actions/github-script@v7.0.1
        id: find_commit
        if: ${{ startsWith(env.SOURCE_BRANCH,'rel-') || env.SOURCE_BRANCH == 'main' }}
        with:
          github-token: ${{ secrets.PIPELINES_REPO_TOKEN  }}
          script: |
            if (${{ github.event_name  == 'workflow_dispatch'}} ){
                core.setOutput('commit_id', "${{ github.sha }}" )
            }
            else{
               core.setOutput('commit_id', "${{ github.event.after }}" )
            }
            
      - name: Get tags
        uses: nick-fields/retry@v3.0.0
        if: ${{ startsWith(env.SOURCE_BRANCH,'rel-') || env.SOURCE_BRANCH == 'main' }}
        with:
          timeout_seconds: 10
          max_attempts: 3
          retry_on: error
          command: |
            git fetch --all
            git tag --contains '${{ steps.find_commit.outputs.commit_id}}'
            latest_tags+=("$(git tag --contains '${{ steps.find_commit.outputs.commit_id }}')")
            if [[ "$latest_tags" == '' ]]; then 
              echo " Tag is Empty"
              exit 1
            fi
            echo "Tag is present: $latest_tags"       
            for tag in $latest_tags; do tag_arr+=($tag); done
            echo "TAGS=${tag_arr[@]}" >> $GITHUB_ENV
      
      
      - name: Find latest tag
        uses: actions/github-script@v7.0.1
        id: latest_tag
        if: ${{ startsWith(env.SOURCE_BRANCH,'rel-') || env.SOURCE_BRANCH == 'main' }}
        with:
          github-token: ${{ secrets.PIPELINES_REPO_TOKEN  }}
          script: |
            console.log("Tags are " + "${{ env.TAGS }}")
            latest_tag = '0.0.0'
            // process multiple tags if any
            tags = "${{ env.TAGS }}".split(' ')
            if (tags.length == 1) {
              console.log("There is only one tag. Using it." + tags[0])
              latest_tag = tags[0]
            } else {
              if ("${{ env.SOURCE_BRANCH }}" == "main") {
                for (i in tags) {
                  tag = tags[i]
                  console.log("Checking tag " + tag)
                  if (latest_tag == null) {
                    latest_tag = tag
                    continue
                  }
                  latest_parts = latest_tag.split(".")
                  tag_parts = tag.split(".")
                  for (i = 0; i < tag_parts.length; i++) {
                    if (parseInt(tag_parts[i]) < parseInt(latest_parts[i])) {
                      console.log("Skipping " + tag)
                      break
                    }
                    if (parseInt(tag_parts[i]) > parseInt(latest_parts[i])) {
                      latest_tag = tag
                      console.log("Setting " + latest_tag)
                      break
                    }
                  }
                }
              } else {
                tag_base = "${{ env.SOURCE_BRANCH }}".substring(4).split(".").slice(0,2)
                latest_tag = tag_base.join(".") + ".0"
                for (i in tags) {
                  tag = tags[i]
                  console.log("branch - Checking tag " + tag)
                  tag_parts = tag.split(".")
                  if (tag_base[0] == tag_parts[0] && tag_base[1] == tag_parts[1]) {
                    latest_parts = latest_tag.split(".")
                    if (parseInt(latest_parts[2]) < parseInt(tag_parts[2])) {
                      latest_tag = tag
                    }
                  }
                }
              }
            }
            console.log("Latest tag: " + latest_tag)
            // check if we have
            if ( latest_tag == '' || latest_tag === undefined) {
              console.log("Couldn't determine the latest tag, exiting. Retry manually..")
              process.exit(1);
            }
            core.setOutput('tag_ref', latest_tag)

      - uses: actions/upload-artifact@v4.3.1
        if: ${{ !startsWith(env.SOURCE_BRANCH,'rel-') && env.SOURCE_BRANCH != 'main' }}
        with:
            name: image-scan-report
            path: ${{ steps.docker-image-scan.outputs.scan-report-path }}
            
      - name: Vulnerability scan
        if: ${{ !startsWith(env.SOURCE_BRANCH,'rel-') && env.SOURCE_BRANCH != 'main' }}
        id: vaulnerability-scan
        env:
          API_URL: http://${{vars.CONVOY_API_ENDPOINT}}/devops/code-scan/vulnerabilities/validate
          REPO: "${{github.repository}}"
          API_KEY: ${{secrets.CONVOY_AUTH_TOKEN}}
          SLACK_TOKEN: ${{secrets.SLACK_TOKEN}}
          DEVOPS_TEAM: ${{secrets.DEVOPS_TEAM_SLACK_ID}}
          CHANNEL_ID: ${{secrets.CONVOY_ALERTS_SLACK_CHANNEL}}
          trivy_version: ${{ vars.TRIVY_VERSION }}
        run: |
          trivy -v
          trivy image -f json -o trivy_image_scan_result.json ${{ env.DOCKER_IMAGE_NAME }}:latest

          python3 - <<EOF
          import requests
          import json
          import os
          import time
          import base64

          API_URL = os.environ.get('API_URL')
          API_KEY = os.environ.get('API_KEY')
          REPO = os.environ.get('REPO')

          def post_to_slack(message):
            usergroup_id=os.environ.get('DEVOPS_TEAM')
            mention = f"<!subteam^{usergroup_id}>"
            full_message=f"{mention}\n vulnerability validation failed, please check \n```{message}```"
            client = WebClient(token=os.environ.get('SLACK_TOKEN'))
            try:
              response = client.chat_postMessage(channel=os.environ.get('CHANNEL_ID'), text=full_message)
              return response["ok"]
            except SlackApiError as e:
              print(f"Error posting to Slack: {e.response['error']}")
              return False

          with open('trivy_image_scan_result.json') as user_file:
            parsed_json = json.load(user_file)
          payload = {
            "repoName": REPO,
            "CVE":parsed_json
          }

          headers = {
            'Content-Type': 'application/json',
            'x-api-key': API_KEY
          }

          max_retries = 3
          retry_delay = 20 
          
          try:
            response = requests.post(API_URL, json=payload, headers=headers)
            if response.status_code == 200:
              print(response.status_code)
              print(response.text)
            elif response.status_code == 409:
              print(response.json())
              print("Get approval for these vulnerabilities or fix them")
              exit(1)
            else:
              print(response.status_code)
              print(response.text)
              post_to_slack(response.text)
              exit(1)
          except Exception as e:
            post_to_slack(response.text)
              exit(1) 
          EOF


      - name: Sign and push docker image
        if: ${{ startsWith(env.SOURCE_BRANCH,'rel-') || env.SOURCE_BRANCH == 'main' }}
        uses: sudo-bot/action-docker-sign@cc41a5b5c636e623b6a1ec8ba4b6eb2fd6369c7a
        with:
          image-ref: "${{ env.DOCKERHUB_ORG }}/${{ env.DOCKER_IMAGE_NAME }}:${{ steps.latest_tag.outputs.tag_ref }}"
          private-key-id: ${{ secrets.DCT_PRIVATE_KEY_ID }}
          private-key: ${{ secrets.DCT_PRIVATE_KEY }}
          private-key-passphrase: ${{ secrets.DCT_PRIVATE_KEY_PASSPHRASE }}
          
      - name: Slack Notification
        uses: act10ns/slack@v2.0.0
        if: ${{ failure() && (startsWith(env.SOURCE_BRANCH,'rel-') || env.SOURCE_BRANCH == 'main') }}
        with:
           status: ${{ job.status }}
           steps: ${{ toJson(steps) }}
           channel: ${{ secrets.SLACK_DEVOPS_CHANNEL  }}

      - name: Get PR-Author,subject & body to send email
        if: ${{ failure() && contains(github.event.pull_request.head.ref, 'double_commit') }}
        run: |
          echo "MAILID=$(git log -1 '${{ github.event.pull_request.head.sha }}' --pretty=format:'%ae')" >> $GITHUB_ENV
          echo "BODY=JOB_STATUS : ${{ job.status }} %0A WORKFLOW : ${{ github.workflow }} %0A EVENT : ${{ github.event_name }} %0A BRANCH : ${{ env.SOURCE_BRANCH }} %0A COMMIT_ID : ${{ github.sha }} %0A REPO : ${{ github.repository }}" >> $GITHUB_ENV
 
      - name: sending output
        if: ${{ failure() && contains(github.event.pull_request.head.ref, 'double_commit') }}
        id: mail_info
        run: |
          echo "mail_id=${{ env.MAILID }}" >> $GITHUB_OUTPUT
          echo "mail_subject=***${{ job.status }}*** || ${{ github.workflow }}  ||  ${{ github.repository }} " >> $GITHUB_OUTPUT
          echo "mail_body=${{ env.BODY }}" >> $GITHUB_OUTPUT
  
  post-build-status-to-convoy:
    runs-on: non-build
    needs: build
    if: always()  
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.CONVOY_ALERTS_SLACK_URL }}
    steps:
      
      - name: Get branch name
        shell: bash
        run: |
          echo "SOURCE_BRANCH=$(echo ${GITHUB_REF#refs/heads/} | tr / -)" >> $GITHUB_ENV

      - uses: technote-space/workflow-conclusion-action@v3.0.3
        with:
          GITHUB_TOKEN: ${{ secrets.CIPIPELINE_GITHUB_TOKEN }}

      - name: POST API to Convoy
        if: ${{ startsWith(env.SOURCE_BRANCH,'rel-') || env.SOURCE_BRANCH == 'main' }}
        env:
          API_URL: http://${{vars.CONVOY_API_ENDPOINT}}/devops/git-metadata/build-status
          COMMIT_HASH: "${{github.sha}}"
          REPO: "${{github.repository}}"
          BASE_BRANCH: "${{github.event.pull_request.base.ref}}"
          API_KEY: ${{secrets.CONVOY_AUTH_TOKEN}}
          STATUS: "${{env.WORKFLOW_CONCLUSION}}"
          SOURCE_BRANCH: "${{env.SOURCE_BRANCH}}"
        run: |
          python3 - <<EOF
          import requests
          import json
          import os
          import time
          import base64

          API_URL = os.environ.get('API_URL')
          API_KEY = os.environ.get('API_KEY')
          REPO = os.environ.get('REPO')
          COMMIT_HASH = os.environ.get('COMMIT_HASH')
          BASE_BRANCH = os.environ.get('BASE_BRANCH')
          STATUS = (os.environ.get('STATUS')).upper()

          if not(bool(BASE_BRANCH)):
            BASE_BRANCH = os.environ.get('SOURCE_BRANCH')
          
          OWNER = REPO.split("/")
          REPO = OWNER[1]
          
          if STATUS == 'SUCCESS':
            STATUS = 'SUCCESSFUL'
          if STATUS == 'FAILURE':
            STATUS = 'FAILED'

          payload = {
            "repoName": REPO,
            "commitHash": COMMIT_HASH[:7],
            "baseBranch": BASE_BRANCH,
            "buildStatus": STATUS
          }

          print(payload)
          headers = {
            'Content-Type': 'application/json',
            'x-api-key': API_KEY
          }

          max_retries = 3
          retry_delay = 20 
      
          for _ in range(max_retries):
              response = requests.post(API_URL, json=payload, headers=headers)
              if response.status_code == 200:
                  print(response.status_code)
                  print(response.text)
                  break
              else:
                  print(response.status_code)
                  print(response.text)
                  print(f"Retrying... ({max_retries - _} attempts left)")
                  time.sleep(retry_delay)
          else:
              print("API request failed after retries.")
              exit(1)
          print("POST request Complete")
          EOF

      - name: Slack Notification
        uses: act10ns/slack@v2.0.0
        with:
            status: ${{ job.status }}
            steps: ${{ toJson(steps) }}
            channel: ${{ secrets.CONVOY_ALERTS_SLACK_CHANNEL  }}
        if: failure()
  
  send-mail:
    uses: ./.github/workflows/email_dc.yaml
    needs: build
    with:
      subject: ${{ needs.build.outputs.mail_subject_output }}
      body: ${{ needs.build.outputs.mail_body_output }} 
      to: ${{ needs.build.outputs.mail_id_output }}
    secrets: inherit
    if: ${{ failure() && contains(github.event.pull_request.head.ref, 'double_commit') }}

            
