---
name: Auto Merge Double Commit PRs
on:
  workflow_call:
    inputs:
      subject:
        description: 'Email subject that is passed from the caller worflow'
        required: true
        type: string
      body:
        description: 'Body of Email that is passed from the caller workflow'
        required: true
        type: string
      to:
        description: 'This is the Receiver of Email'
        required: true
        type: string
jobs:
  email_dc:
    runs-on: self-hosted
    steps:
      - name: Send Email to PR Author
        uses: wadeww/send-email-action@master
        with:
          server_address:  ${{ secrets.EMAIL_SERVER_ADDRESS }}
          port: ${{ secrets.EMAIL_PORT }}
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: ${{ inputs.subject }}
          body: ${{ inputs.body }}
          to: ${{ inputs.to }},${{ secrets.CIPIPELINE_USER_EMAIL }}
          from: ${{ secrets.CIPIPELINE_USER_EMAIL }}
