name: Check Changed Files

# Controls when the workflow will run
on:
  workflow_call:
    outputs:
        specific:
          description: "Changed File output"
          value: ${{ jobs.file-check.outputs.specific }}
        word:
            description: "Changed File output"
            value: ${{ jobs.file-check.outputs.hello }}   
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  file-check:
    runs-on: self-hosted
    outputs:
      specific: ${{steps.check-file-output.outputs.specific}}
      hello: ${{steps.check-file-output.outputs.hello}}
    name: Check changed files
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 
      - name: Changed files
        id: changed-files-specific
        uses: tj-actions/changed-files@v39
        with:
          files: |
            .github/**
      - name: Set Output
        id: check-file-output
        run: |
          echo "specific=${{steps.changed-files-specific.outputs.only_changed}}" >> $GITHUB_OUTPUT
          echo "hello=hello" >> $GITHUB_OUTPUT