---
name: Tessell Pipelines Code Build for PR

on:
  workflow_call:
    inputs:
      type:
        description: 'This is used to determine build type'
        required: true
        type: string

  workflow_dispatch:

jobs:
  build-ubuntu:
    if: ${{inputs.type != 'GRAALVM' }}
    runs-on: self-hosted
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL  }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
  
  build-macos:
    if: ${{inputs.type == 'GRAALVM' }}
    runs-on: self-hosted
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL  }}
    steps:

      - name: Build OPS
        run: |
          ./mvnw install
          mv target project
          cd project 
          ls
          cd ..
          ./mvnw install -Dnative -DskipTests -Dquarkus.native.container-build=true
          cd project
          ls
          cd ..
          mv project target
          echo "Build successful"