---
name: Service Manifest PATCH API to Convoy
on:
  workflow_call:
    
jobs:
  
  patch-service-manifest-to-convoy:
    runs-on: non-build
    env: 
      SLACK_WEBHOOK_URL: ${{ secrets.CONVOY_ALERTS_SLACK_URL }}
    steps:

      - name: PATCH API to Convoy
        run: |
          TOKEN=$(echo -n '${{secrets.CIPIPELINE_NEXUS_USERNAME}}:${{secrets.CIPIPELINE_NEXUS_PASSWORD}}' | base64)
          curl --location --request PATCH 'http://${{vars.CONVOY_DEV_API_ENDPOINT}}/devops/applications/app-groups/service-manifest' \
            --header 'Authorization: Basic $TOKEN' \
            --data ''

      - name: Slack Notification
        uses: act10ns/slack@v1.5.0
        with:
            status: ${{ job.status }}
            steps: ${{ toJson(steps) }}
            channel: ${{ secrets.CONVOY_ALERTS_SLACK_CHANNEL  }}
        if: failure()
          