---
name: Tessell Pipelines Code Build Pre Merge
on:
  workflow_call:
    inputs:
      type:
        description: 'This is used to determine build type'
        required: true
        type: string

jobs:

  build-ui:
    if: ${{ inputs.type == 'ui-build' }}
    runs-on: ui-build
    env:
      CI-BRANCH: TDEVOPS-1832
      GITHUB_TOKEN: ${{ secrets.CIPIPELINE_GITHUB_TOKEN }}  
      GITHUB_USER: ${{ secrets.CIPIPELINE_GITHUB_USER }}
      NEXUS_PASSWORD: ${{secrets.CIPIPELINE_NEXUS_PASSWORD}}
      NEXUS_PROTOCOL: ${{vars.NEXUS_PROTOCOL_PUBLIC}}
      NEXUS_PULL_REPOS_M2: tessell-m2-development
      NEXUS_REPO_NPM: tessell-repos-npm-development
      NEXUS_SERVER_ENDPOINT: ${{vars.NEXUS_SERVER_ENDPOINT_PUBLIC}}
      NEXUS_USERNAME: ${{secrets.CIPIPELINE_NEXUS_USERNAME}}
      TESSELL_UI_ENV_SECRET: '${{secrets.TESSELL_UI_ENV_SECRET}}'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0

      - name: Setup CI Scripts
        run: |
          cd ~/convoy-ci
          git checkout ${{env.CI-BRANCH}}
          git pull
          cd ~-
          cp -r ~/convoy-ci/.github/scripts ./scripts

      - name: Build
        shell: bash
        run: |
          bash ./scripts/bash/build.sh build
  
  build-ubuntu-latest:
    if: ${{ inputs.type == 'ubuntu-latest' }}
    runs-on: ubuntu-latest
    env:
      CI-BRANCH: TDEVOPS-1832
      CHANNEL_ID: ${{vars.CONVOY_ALERTS_SLACK_ID}}
      CONVOY_API_KEY: ${{secrets.CONVOY_AUTH_TOKEN}}
      DEVOPS_TEAM: ${{vars.DEVOPS_TEAM_SLACK_ID}}
      IMAGE_SCAN_API_URL: http://${{vars.CONVOY_PUBLIC_API_ENDPOINT}}/devops/code-scan/vulnerabilities/validate
      GITHUB_USER: ${{ secrets.CIPIPELINE_GITHUB_USER }}
      GITHUB_TOKEN: ${{ secrets.CIPIPELINE_GITHUB_TOKEN }}
      NEXUS_PASSWORD: ${{secrets.CIPIPELINE_NEXUS_PASSWORD}}
      NEXUS_PROTOCOL: ${{vars.NEXUS_PROTOCOL_PUBLIC}}
      NEXUS_PULL_REPOS_PY: tessell-py-development
      NEXUS_PULL_REPOS_M2: tessell-m2-development
      NEXUS_USERNAME: ${{secrets.CIPIPELINE_NEXUS_USERNAME}}
      NEXUS_SERVER_ENDPOINT: ${{vars.NEXUS_SERVER_ENDPOINT_PUBLIC}}
      REPO: "${{github.repository}}"
      SLACK_TOKEN: ${{secrets.SLACK_TOKEN}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0

      - name: Setup CI Scripts
        run: |
          git clone https://${{env.GITHUB_USER}}:${{env.GITHUB_TOKEN}}@github.com/TessellDevelopment/convoy-ci.git
          cd convoy-ci
          git checkout ${{env.CI-BRANCH}}
          git pull
          cd ..
          cp -r ./convoy-ci/.github/scripts ./scripts

      - name: Set up Python
        uses: actions/setup-python@v5.0.0
        with:
          python-version: 3.9

      - name: Setup Go
        uses: actions/setup-go@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v4.0.0
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3.0.0

      - name: Login to docker
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Create pip conf
        run: |
          bash ./scripts/bash/dependency.sh createPipConf
        shell: bash

      - name: Install dependencies
        run: |
          bash ./scripts/bash/dependency.sh installPythonDependencies

      - name: Setup Trivy and Dockle
        run: |
          bash ./scripts/bash/dependency.sh setupTrivyDockle

      - name: Build
        shell: bash
        run: |
          bash ./scripts/bash/build.sh build

  build-amd-go-20:
    if: ${{ inputs.type == 'amd-go-20' }}
    runs-on: amd-go-20
    env:
      CI-BRANCH: TDEVOPS-1832
      CHANNEL_ID: ${{vars.CONVOY_ALERTS_SLACK_ID}}
      CONVOY_API_KEY: ${{secrets.CONVOY_AUTH_TOKEN}}
      DEVOPS_TEAM: ${{vars.DEVOPS_TEAM_SLACK_ID}}
      IMAGE_SCAN_API_URL: http://${{vars.CONVOY_API_ENDPOINT}}/devops/code-scan/vulnerabilities/validate
      GITHUB_USER: ${{ secrets.CIPIPELINE_GITHUB_USER }}
      GITHUB_TOKEN: ${{ secrets.CIPIPELINE_GITHUB_TOKEN }}
      NEXUS_PASSWORD: ${{secrets.CIPIPELINE_NEXUS_PASSWORD}}
      NEXUS_PROTOCOL: ${{vars.NEXUS_PROTOCOL_PUBLIC}}
      NEXUS_SERVER_ENDPOINT: ${{vars.NEXUS_SERVER_ENDPOINT_PUBLIC}}
      NEXUS_USERNAME: ${{secrets.CIPIPELINE_NEXUS_USERNAME}}
      REPO: "${{github.repository}}"
      SLACK_TOKEN: ${{secrets.SLACK_TOKEN}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0

      - name: Setup CI Scripts
        run: |
          cd ~/convoy-ci
          git checkout ${{env.CI-BRANCH}}
          git pull
          cd ~-
          cp -r ~/convoy-ci/.github/scripts ./scripts

      - name: Check go Config
        run: |
          go version
          echo $GOPATH
          echo $GOROOT
          echo $PATH
          go env
          
      - name: Build
        shell: bash
        run: |
          bash ./scripts/bash/build.sh build

      - name: Cleanup
        if: always()
        run: |
          set +e
          docker container prune --force
          docker volume prune --force

  build-amd-go-21:
    if: ${{ inputs.type == 'amd-go-21' }}
    runs-on: amd-go-21
    env:
      CI-BRANCH: TDEVOPS-1832
      CHANNEL_ID: ${{vars.CONVOY_ALERTS_SLACK_ID}}
      CONVOY_API_KEY: ${{secrets.CONVOY_AUTH_TOKEN}}
      DEVOPS_TEAM: ${{vars.DEVOPS_TEAM_SLACK_ID}}
      IMAGE_SCAN_API_URL: http://${{vars.CONVOY_API_ENDPOINT}}/devops/code-scan/vulnerabilities/validate
      GITHUB_USER: ${{ secrets.CIPIPELINE_GITHUB_USER }}
      GITHUB_TOKEN: ${{ secrets.CIPIPELINE_GITHUB_TOKEN }}
      NEXUS_PASSWORD: ${{secrets.CIPIPELINE_NEXUS_PASSWORD}}
      NEXUS_PROTOCOL: ${{vars.NEXUS_PROTOCOL_LOCAL}}
      NEXUS_SERVER_ENDPOINT: ${{vars.NEXUS_SERVER_ENDPOINT_LOCAL}}
      NEXUS_USERNAME: ${{secrets.CIPIPELINE_NEXUS_USERNAME}}
      REPO: "${{github.repository}}"
      SLACK_TOKEN: ${{secrets.SLACK_TOKEN}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0

      - name: Setup CI Scripts
        run: |
          cd ~/convoy-ci
          git checkout ${{env.CI-BRANCH}}
          git pull
          cd ~-
          cp -r ~/convoy-ci/.github/scripts ./scripts

      - name: Check go Config
        run: |
          go version
          echo $GOPATH
          echo $GOROOT
          echo $PATH
          go env
          
      - name: Build
        shell: bash
        run: |
          bash ./scripts/bash/build.sh build

      - name: Cleanup
        if: always()
        run: |
          set +e
          docker container prune --force
          docker volume prune --force

  build-amd:
    if: ${{ inputs.type == 'amd' }}
    runs-on: self-hosted
    env:
      CI-BRANCH: TDEVOPS-1832
      CHANNEL_ID: ${{vars.CONVOY_ALERTS_SLACK_ID}}
      CONVOY_API_KEY: ${{secrets.CONVOY_AUTH_TOKEN}}
      DEVOPS_TEAM: ${{vars.DEVOPS_TEAM_SLACK_ID}}
      IMAGE_SCAN_API_URL: http://${{vars.CONVOY_API_ENDPOINT}}/devops/code-scan/vulnerabilities/validate
      GITHUB_USER: ${{ secrets.CIPIPELINE_GITHUB_USER }}
      GITHUB_TOKEN: ${{ secrets.CIPIPELINE_GITHUB_TOKEN }}
      GOPATH: /home/github/go
      NAMESPACE: "convoy"
      NEXUS_PASSWORD: ${{secrets.CIPIPELINE_NEXUS_PASSWORD}}
      NEXUS_PROTOCOL: ${{vars.NEXUS_PROTOCOL_LOCAL}}
      NEXUS_SERVER_ENDPOINT: ${{vars.NEXUS_SERVER_ENDPOINT_LOCAL}}
      NEXUS_PULL_REPOS_M2: tessell-m2-development
      NEXUS_PULL_REPOS_PY: tessell-py-development
      NEXUS_USERNAME: ${{secrets.CIPIPELINE_NEXUS_USERNAME}}
      OWNER: ${{github.repository_owner}}
      REPO: "${{github.repository}}"
      SLACK_TOKEN: ${{secrets.SLACK_TOKEN}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0

      - name: Setup CI Scripts
        run: |
          cd ~/convoy-ci
          git checkout ${{env.CI-BRANCH}}
          git pull
          cd ~-
          cp -r ~/convoy-ci/.github/scripts ./scripts

      - name: Check specific file changes
        id: changed-files
        uses: tj-actions/changed-files@v42.0.2
        with:
          files: |
            Chart.yaml
            services/**
            scripts/Dockerfile
            scripts/initializeAutomation.sh

      - name: Check All file changes
        id: changed-files-all
        uses: tj-actions/changed-files@v42.0.2

      - name: Login to docker
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build
        env:
          CHANGED_FILES_ANY_MODIFIES: ${{steps.changed-files.outputs.any_modified}}
          CHANGED_AND_MODIFIED_FILES: ${{steps.changed-files-all.outputs.all_changed_and_modified_files}}
        shell: bash
        run: |
          bash ./scripts/bash/build.sh build

      - name: Cleanup
        if: always()
        run: |
          set +e
          sudo rm -rf target
          docker container prune --force
          docker volume prune --force

  build-arm:
    if: ${{ inputs.type == 'arm' }}
    runs-on: ARM64
    env:
      CI-BRANCH: TDEVOPS-1832
      CHANNEL_ID: ${{vars.CONVOY_ALERTS_SLACK_ID}}
      CONVOY_API_KEY: ${{secrets.CONVOY_AUTH_TOKEN}}
      DEVOPS_TEAM: ${{vars.DEVOPS_TEAM_SLACK_ID}}
      GITHUB_USER: ${{ secrets.CIPIPELINE_GITHUB_USER }}
      GITHUB_TOKEN: ${{ secrets.CIPIPELINE_GITHUB_TOKEN }}
      IMAGE_SCAN_API_URL: http://${{vars.CONVOY_API_ENDPOINT}}/devops/code-scan/vulnerabilities/validate
      NEXUS_PASSWORD: ${{secrets.CIPIPELINE_NEXUS_PASSWORD}}
      NEXUS_PROTOCOL: ${{vars.NEXUS_PROTOCOL_LOCAL}}
      NEXUS_SERVER_ENDPOINT: ${{vars.NEXUS_SERVER_ENDPOINT_LOCAL}}
      NEXUS_USERNAME: ${{secrets.CIPIPELINE_NEXUS_USERNAME}}
      REPO: "${{github.repository}}"
      SLACK_TOKEN: ${{secrets.SLACK_TOKEN}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0

      - name: Setup CI Scripts
        run: |
          cd ~/convoy-ci
          git checkout ${{env.CI-BRANCH}}
          git pull
          cd ~-
          cp -r ~/convoy-ci/.github/scripts ./scripts

      - name: Build
        shell: bash
        run: |
          bash ./scripts/bash/build.sh build

      - name: Cleanup
        if: always()
        run: |
          set +e
          sudo rm -rf target
          docker container prune --force
          docker volume prune --force
