---
name: Create PR for double merge
on:
  workflow_call:

jobs:

  create-pr-for-double-merge:
    if: github.event.pull_request.merged == true
    runs-on: non-build
    env:
      CI_BRANCH: main
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL  }}
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
          token: ${{secrets.CIPIPELINE_GITHUB_TOKEN}}

      - name: Setup CI Scripts
        run: |
          cd ~/convoy-ci
          git checkout main
          git pull
          git checkout ${{env.CI_BRANCH}}
          git pull
          cd ~-
          cp -r ~/convoy-ci/.github/ci-scripts ./ci-scripts

      - name: Create Double Commit PRs
        env:
          COMMIT_SHA: ${{ github.sha }}
          GITHUB_TOKEN: ${{ secrets.CIPIPELINE_GITHUB_TOKEN }}
          MAILID: ${{ github.event.pull_request.user.email }}
          PR_BASE_BRANCH: ${{ github.event.pull_request.base.ref }}
          PR_HEAD_BRANCH: ${{ github.event.pull_request.head.ref }}
          PR_TITLE: ${{ github.event.pull_request.title }}
          REPO_OWNER: ${{ github.repository_owner }}
          REPO_NAME: ${{ github.event.repository.name }}
        run: |
          bash ./ci-scripts/bash/create-double-commit

      - name: Slack Notification
        if: failure()
        uses: act10ns/slack@v2.0.0
        with:
           status: ${{ job.status }}
           steps: ${{ toJson(steps) }}
           channel: ${{ secrets.SLACK_DEVOPS_CHANNEL  }}
