name: Cherry Pick workflow
on:
  workflow_call:
    inputs: 
      base-repo: 
        description: 'Base repo url to get changes'
        required: true
        type: string
      jira:
        description: 'Jira ID for cherry pick'
        required: true
        type: string
      pr-title:
        description: 'PR Title for cherry pick'
        required: true
        type: string

  workflow_dispatch:

jobs:
  cherry-pick:
    runs-on: self-hosted
    env: 
      URL: "${{inputs.base-repo}}"
      REPO: "${{github.repository}}"
      JIRA: "${{inputs.jira}}"
      PR_TITLE: "${{inputs.pr-title}}"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Cherry Pick changes from FRP repo
        run: |
          #!/bin/bash
          set +e
          git remote add upstream $URL
          git fetch upstream master
          git checkout -b $JIRA
          logs=$(git cherry-pick -m 1 upstream/master)
          echo "$logs"
          while IFS= read -r line; do
            echo "$line"
            if [[ $line == CONFLICT* ]]; then
              file_path=$(echo "$line" | awk '{print $3}')
              if [[ $file_path == 'Merge' ]]; then
                file_path=$(echo "$line" | awk '{print $6}')
                echo "$file_path"
                git add $file_path
              else
                echo "$file_path"
                git rm $file_path
              fi
            fi
          done <<< "$logs"
          git add .
          git commit -m "$PR_TITLE"
          git push origin $JIRA

          curl -X POST -H "Authorization: token ${{ secrets.CIPIPELINE_NEXUS_PASSWORD }}" \
            -d '{"title": "$PR_TITLE", "head": "$JIRA", "base": "main"}' \
            "https://api.github.com/repos/$REPO/pulls"