---
name: Master CI Approve Workflows
on:
  workflow_call:

  workflow_dispatch:

jobs:
  file-check:
    uses: TessellDevelopment/tessell-ci/.github/workflows/master_file_check.yml@TDEVOPS-827
    secrets: inherit
  
  read-codeowners:
    needs: file-check
    uses: TessellDevelopment/tessell-ci/.github/workflows/master_read_codeowners.yml@TDEVOPS-827
    with:
      changed-files: ${{needs.file-check.outputs.changed-files}}
    secrets: inherit
    
  # check-label:
  #   needs: read-codeowners
  #   uses: TessellDevelopment/tessell-ci/.github/workflows/master_check_label.yml@TDEVOPS-827
  #   with:
  #     required-teams: ${{needs.read-codeowners.outputs.required-teams}}
  #   secrets: inherit

  post-message: 
    if: ${{ github.event.action == 'opened' || github.event.action == 'synchronize' }}
    needs: read-codeowners
    uses: TessellDevelopment/tessell-ci/.github/workflows/master_post_message.yml@TDEVOPS-827
    secrets: inherit
    with:
      required-teams: ${{needs.read-codeowners.outputs.required-teams}}

  check-approval:
    if: github.event.review.state == 'approved'
    needs: read-codeowners
    uses: TessellDevelopment/tessell-ci/.github/workflows/master_check_approval.yml@TDEVOPS-827
    secrets: inherit
    with:
      required-teams: ${{needs.read-codeowners.outputs.required-teams}}