---
name: Tessell Pipelines Code Build Pre Merge
on:
  workflow_call:
    inputs:
      type:
        description: 'This is used to determine build type'
        required: true
        type: string

jobs:

  build-amd:
    if: ${{inputs.type != 'quarkus' }}
    runs-on: amd64
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL  }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
  
  build-arm:
    if: ${{inputs.type == 'quarkus' }}
    runs-on: ARM64
    env:
      DOCKERHUB_ORG: tesselldev
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL  }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: aws-actions/setup-sam@v2
        with:
          use-installer: true

      - name: Build
        run: |
          mvnw() {
            sudo ./mvnw install -Dnative -DskipTests -Dquarkus.native.container-build=true
          }
          docker() {
            IMAGE_NAME="$1"
            FILE="$4"
            sudo ./mvnw install -Dnative -DskipTests -Dquarkus.native.container-build=true
            docker build -f $FILE -t ${DOCKERHUB_ORG}/$IMAGE_NAME:${{github.head_ref}} .
            docker push ${DOCKERHUB_ORG}/$IMAGE_NAME:${{github.head_ref}}
          }
          makefile(){

          }
          build() {
            type="$1"
            check=$(grep "$type" convoy.yaml)
            if [[ -z "$check" ]]; then
              return
            fi
            while IFS=$'\t' read -r name buildFunction ext version file _; do
              echo "$name"
              echo "$buildFunction"
              echo "$ext"
              echo "$version"
              echo "$file"
              $buildFunction "$name" "$ext" "$version" "$file"
            done < <(yq e ".generates.$type[] | [.name, .buildFunction, .extension, .version, .dockerFile] | @tsv" convoy.yaml)
          }
          build "artifacts"
          build "dockerImages"

      - name: Remove target
        if: always()
        run: |
          sudo rm -rf target
          