---
name: Post message for review

on:
  workflow_call:
    inputs:
      required-teams:
        description: 'Teams required for approval in the PR'
        required: true
        type: string

  workflow_dispatch:

jobs:
  post-message:
    runs-on: amd64
    env:
      TOKEN: ${{ secrets.CIPIPELINE_NEXUS_PASSWORD }}
    steps: 
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.CIPIPELINE_NEXUS_PASSWORD  }}
          fetch-depth: 0
          
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"

      # - name: Get team members names
      #   id: team_members
      #   run: |
      #     ORG_NAME="TessellDevelopment"
      #     TEAM_NAME="${{github.event.label.name}}"
      #     MEMBERS=$(curl -s -H "Authorization: Bearer $TOKEN" "https://api.github.com/orgs/$ORG_NAME/teams/$TEAM_NAME/members" | jq -r '.[].login')
      #     IFS=, read -r -a array <<< "$(echo -e "$MEMBERS" | tr '\n' ',')"
      #     MESSAGE="Files changed in your PR requires approval from $TEAM_NAME team. Please get approval from:"
      #     for member in "${array[@]}"; do
      #       MESSAGE="$MESSAGE <br /> $member"
      #     done
      #     echo "message=$MESSAGE" >> $GITHUB_OUTPUT

      - name: Check message exists
        id: check-message
        run: |
          #!/bin/bash
          set +e
          ORG_NAME="TessellDevelopment"
          REPO="${{github.repository}}"
          PR_NUMBER="${{ github.event.pull_request.number }}"
          COMMIT_HASH="${{github.event.after}}"
          TEAMS="${{inputs.required-teams}}"
          COMMENT_ID=$(curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/repos/$REPO/issues/$PR_NUMBER/comments" | jq -r  '.[] | select(.body|test("^Commit hash.")) | .id')
          echo "$COMMENT_ID"
          MESSAGE="Commit hash: $COMMIT_HASH <br />Required Approvals:"
          IFS=' ' read -ra TEAMS_ARRAY <<< "$TEAMS"
          for TEAM in "${TEAMS_ARRAY[@]}"; do
            MESSAGE="$MESSAGE <br /> @TessellDevelopment/$TEAM"
          done
          echo "message=$MESSAGE" >> $GITHUB_OUTPUT
          if [ -z "$COMMENT_ID" ]
          then
            echo "check=false" >> $GITHUB_OUTPUT
          else
            echo "check=true" >> $GITHUB_OUTPUT
            echo "comment-id=$COMMENT_ID" >> $GITHUB_OUTPUT
          fi

      - name: Create message
        if: steps.check-message.outputs.check == 'false'
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.pull_request.number }}
          token: ${{ secrets.CIPIPELINE_NEXUS_PASSWORD }}
          body: ${{steps.check-message.outputs.message}}

      - name: Update message
        if: steps.check-message.outputs.check == 'true'
        uses: peter-evans/create-or-update-comment@v3
        with:
          comment-id: ${{steps.check-message.outputs.comment-id}}
          token: ${{ secrets.CIPIPELINE_NEXUS_PASSWORD }}
          body: ${{steps.check-message.outputs.message}}