---
name: Master CI Approve Workflows
on:
  workflow_call:

jobs:
  
  file-check:
    uses: TessellDevelopment/convoy-ci/.github/workflows/master_file_check.yml@TDEVOPS-827
    secrets: inherit
  
  read-codeowners:
    needs: file-check
    uses: TessellDevelopment/convoy-ci/.github/workflows/master_read_codeowners.yml@TDEVOPS-827
    secrets: inherit
    with:
      changed-files: ${{needs.file-check.outputs.changed-files}}

  post-message: 
    if: ${{ github.event.action == 'opened' || github.event.action == 'synchronize' }}
    needs: read-codeowners
    uses: TessellDevelopment/convoy-ci/.github/workflows/master_post_message.yml@TDEVOPS-827
    secrets: inherit
    with:
      required-teams: ${{needs.read-codeowners.outputs.required-teams}}

  check-approval:
    if: github.event.review.state == 'approved'
    needs: read-codeowners
    uses: TessellDevelopment/convoy-ci/.github/workflows/master_check_approval.yml@TDEVOPS-827
    secrets: inherit
    with:
      required-teams: ${{needs.read-codeowners.outputs.required-teams}}
      
