---
name: Check Changed Files

on:
  workflow_call:
  workflow_dispatch:

jobs:
  post-message:
    runs-on: self-hosted
    env:
      TOKEN: ${{ secrets.CIPIPELINE_NEXUS_PASSWORD }}
    steps: 
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"

      - name: Get team members names
        id: team_members
        run: |
          ORG_NAME="TessellDevelopment"
          TEAM_NAME="${{github.event.label.name}}"
          MEMBERS=$(curl -s -H "Authorization: Bearer $TOKEN" "https://api.github.com/orgs/$ORG_NAME/teams/$TEAM_NAME/members" | jq -r '.[].login')
          IFS=, read -r -a array <<< "$(echo -e "$MEMBERS" | tr '\n' ',')"
          MESSAGE="Files changed in your PR requires approval from $TEAM_NAME team. Please get approval from:"
          for member in "${array[@]}"; do
            MESSAGE="$MESSAGE\n$member"
          done
          echo "message=$MESSAGE" >> $GITHUB_OUTPUT

      - name: Post team members name message
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: ${{steps.team_members.outputs.message}}
          GITHUB_TOKEN: ${{ secrets.CIPIPELINE_NEXUS_PASSWORD }}
          pr_number: ${{ github.event.pull_request.number }}
          