---
name: Find latest tag
on:
  workflow_call:
    outputs:
      tag:
        description: "Latest tag"
        value: ${{ jobs.find-latest-tag.outputs.tag_ref_output }}
  
jobs:

  find-latest-tag:
    runs-on: non-build
    env:
      CI-BRANCH: TDEVOPS-1832
      GITHUB_TOKEN: ${{ secrets.CIPIPELINE_GITHUB_TOKEN  }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL  }}
    outputs:
      tag_ref_output: ${{ steps.tag_output.outputs.tag_ref }}
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"

      - name: Setup CI Scripts
        run: |
          cd ~/convoy-ci
          git checkout ${{env.CI-BRANCH}}
          git pull
          cd ~-
          cp -r ~/convoy-ci/.github/scripts ./scripts
          
      - name: Get branch name
        shell: bash
        run: |
          echo "SOURCE_BRANCH=$(echo ${GITHUB_REF#refs/heads/} | tr / -)" >> $GITHUB_ENV
              
      - name: Get tags
        uses: nick-fields/retry@v3.0.0
        with:
          timeout_seconds: 10
          max_attempts: 3
          retry_on: error
          command: |
            git fetch --all
            sha="${{github.sha}}"
            sha="${sha:0:7}"
            echo "$(git log --decorate --oneline)"
            latest_tags="$(git log --decorate --oneline | grep $sha | grep -o -E "tag: [0-9]+\.[0-9]+\.[0-9]+" | awk '{print $2}')"
            if [[ "$latest_tags" == '' ]]; then 
              echo "Tag is Empty"
              exit 1
            fi
            echo "Tag is present: $latest_tags"       
            for tag in $latest_tags; do tag_arr+=($tag); done
            echo "TAGS=${tag_arr[@]}" >> $GITHUB_ENV
        
        
      - name: Find latest tag
        id: latest_tag
        env:
          SOURCE_BRANCH: "${{env.SOURCE_BRANCH}}"
          TAGS: "${{env.TAGS}}"
        run: |
          node ./scripts/javascript/findLatestTag.js

      - name: Tag Output
        id: tag_output
        run: |
          echo "tag_ref=${{steps.latest_tag.outputs.tag_ref}}" >> $GITHUB_OUTPUT
          
      - name: Slack Notification
        if: failure()
        uses: act10ns/slack@v2.0.0
        with:
            status: ${{ job.status }}
            steps: ${{ toJson(steps) }}
            channel: ${{ secrets.SLACK_DEVOPS_CHANNEL  }}