---
name: Execute Deployment Script
on:
  workflow_call:
    inputs:
      CD_COMMAND:
        required: true
        type: string

jobs:
  deploy-tenant:
    runs-on: non-build
    env:
      TESSELL_GCP_APP_NAME: ${{ vars.TESSELL_GCP_APP_NAME }}
      TESSELL_GCP_SERVICE_ACCOUNT_NAME: ${{vars.TESSELL_GCP_SERVICE_ACCOUNT_NAME}}
      TESSELL_GCP_PROJECT_ID: ${{vars.TESSELL_GCP_PROJECT_ID}}
      BASE_BRANCH: "${{github.event.pull_request.base.ref}}"
      CD_COMMAND: "${{inputs.CD_COMMAND}}"

    steps:

      - name: Checkout code
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0

      - name: Set Application Name
        run: |
          export APP_GROUP=$(yq '.appGroup // "tessell"' convoy.yaml)
          echo "APP_GROUP=$APP_GROUP" >> $GITHUB_ENV

      - name: Login gcloud
        id: auth
        if: ${{ env.APP_GROUP == env.TESSELL_GCP_APP_NAME }}
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.TESSELL_GCP_SERVICE_ACCOUNT_KEY_JSON }}'
          token_format: access_token
          create_credentials_file: true

      - name: Execute Deployment Script
        if: ${{ env.DEPLOY_COMMAND != null }}
        run: |
          echo ${CD_COMMAND}
          ${DEPLOY_COMMAND}
