---
name: Master CI Merge Workflows
on:
  workflow_call:

  workflow_dispatch:

jobs:
  file-check:
    uses: TessellDevelopment/tessell-ci/.github/workflows/master_file_check.yml@TDEVOPS-827
    secrets: inherit

  build-file:
    runs-on: self-hosted
    if: needs.file-check.outputs.github-changes == 'false'
    outputs:
      type: ${{steps.build-type.outputs.type}}
    needs: file-check
    steps:
      - name: Determine build type from Convoy
        id: build-type
        run: |
          build_line=$(grep 'build:' convoy.yaml)
          build_type=$(echo "$build_line" | awk '{print $2}')
          echo "type=$build_type" >> $GITHUB_OUTPUT
  
  create-tag:
    uses: TessellDevelopment/tessell-ci/.github/workflows/master_create_tag.yml@TDEVOPS-827
    secrets: inherit

  post-tag-to-convoy:
    needs: create-tag
    uses: TessellDevelopment/tessell-ci/.github/workflows/master_post_tag_convoy.yml@TDEVOPS-827
    secrets: inherit
    with:
      tag: ${{needs.create-tag.outputs.tag}}

  find-latest-tag:
    needs: create-tag
    uses: TessellDevelopment/tessell-ci/.github/workflows/master_find_latest_tag.yml@TDEVOPS-827
    secrets: inherit

  build:
    needs: [build-file,find-latest-tag]
    uses: TessellDevelopment/tessell-ci/.github/workflows/master_build_merge.yml@TDEVOPS-827
    secrets: inherit
    with:
      type: ${{needs.build-file.outputs.type}}
      tag: ${{needs.find-latest-tag.outputs.tag}}

  post-build-to-convoy:
    if: ${{needs.file-check.outputs.github-changes == 'false' && always()}}
    needs: build
    uses: TessellDevelopment/tessell-ci/.github/workflows/master_post_build_convoy.yml@TDEVOPS-827
    secrets: inherit

  create-double-commit:
    if: startsWith(github.event.pull_request.base.ref, 'rel')
    needs: build
    uses: TessellDevelopment/tessell-ci/.github/workflows/master_create_double_commit.yml@TDEVOPS-827
    secrets: inherit
