---
name: Tessell Pipelines Code Build for PR

on:
  workflow_call:
    inputs:
      type:
        description: 'This is used to determine build type'
        required: true
        type: string

  workflow_dispatch:

jobs:
  build-amd:
    if: ${{inputs.type != 'GRAALVM' }}
    runs-on: amd64
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL  }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
  
  build-arm:
    if: ${{inputs.type == 'GRAALVM' }}
    runs-on: ARM64
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL  }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build OPS
        run: |
          sudo ./mvnw install -Dnative -DskipTests -Dquarkus.native.container-build=true
          echo "Build successful"
          sudo rm -rf target