#After getting teams name required from codeowners check labels if present for that team, if not create a label for that team
---
name: Check Changed Files

on:
  workflow_call:
    inputs:
      required-teams:
        description: 'Teams required for approval in the PR'
        required: true
        type: string

  workflow_dispatch:

jobs:
  check-labels:
    runs-on: self-hosted
    steps:
      - name: Check all labels
        id: check-label
        run: |
          PR_NUMBER="${{ github.event.pull_request.number }}"
          LABELS=$(curl -s -H "Authorization: Bearer ${{secrets.CIPIPELINE_NEXUS_PASSWORD}}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/${PR_NUMBER}" | \
            jq -r '.labels[].name' | tr '\n' ' ')
          if [ -z "$LABELS" ]; then
            echo "create_label=$req_teams" >> $GITHUB_OUTPUT
            exit 0
          fi
          IFS=' ' read -ra LABEL_ARRAY <<< "$LABELS"
          for LABEL in "${LABEL_ARRAY[@]}"; do
            req_teams=${req_teams//"$LABEL"/}
          done
          req_teams=$(echo "$req_teams" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')
          echo "create_label=$req_teams" >> $GITHUB_OUTPUT

      - name: Create Labels
        run: |
          LABELS=${{ steps.check-label.outputs.create_label }}
          LABELS=$(echo "$LABELS" | tr ' ' '\n')
          for label in $LABELS; do
            curl -X POST "https://api.github.com/repos/${{ github.repository }}/issues/$PR_NUMBER/labels" \
              -H "Authorization: token ${{secrets.CIPIPELINE_NEXUS_PASSWORD}}" \
              -d "{\"labels\":[\"$label\"]}"
          done
          