name: Cherry Pick workflow
on:
  workflow_call:
    inputs: 
      base_repo: 
        description: 'Base repo url to get changes'
        required: true
        type: string
      jira_id:
        description: 'Jira ID for cherry pick'
        required: true
        type: string
      pr_title:
        description: 'PR Title for cherry pick'
        required: true
        type: string

  workflow_dispatch:

jobs:
  cherry_pick:
    runs-on: non-build
    env: 
      CI-BRANCH: TDEVOPS-1832
      GITHUB_TOKEN: ${{ secrets.CIPIPELINE_GITHUB_TOKEN }}
      JIRA_ID: "${{inputs.jira_id}}"
      PR_TITLE: "${{inputs.pr_title}}"
      REPO: ${{github.repository}}
      URL: ${{inputs.base_repo}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0

      - name: Setup CI Scripts
        run: |
          cd ~/convoy-ci
          git checkout ${{env.CI-BRANCH}}
          git pull
          cd ~-
          cp -r ~/convoy-ci/.github/scripts ./scripts
      
      - name: Cherry Pick changes from FRP repo
        run: |
          bash ./scripts/bash/cherry_pick.sh
