---
name: Execute Deployment script
on:
  workflow_call:

jobs:
  exec-deploy-script:
    runs-on: self-hosted
    env:
      BASE_BRANCH: "${{github.event.pull_request.base.ref}}"
      TESSELL_GCP_APP_NAME: ${{ vars.TESSELL_GCP_APP_NAME }}
      TESSELL_GCP_PROJECT_ID: ${{vars.TESSELL_GCP_PROJECT_ID}}
      TESSELL_GCP_SERVICE_ACCOUNT_NAME: ${{vars.TESSELL_GCP_SERVICE_ACCOUNT_NAME}}

    steps:
      - name: Set Application Name
        run: |
          export APP_GROUP=$(yq '.appGroup // "tessell"' convoy.yaml)
          echo "APP_GROUP=$APP_GROUP" >> $GITHUB_ENV

      - name: Set Deploy Command
        run: |
          DEPLOY_COMMAND=$(yq '.cd.exec // null' convoy.yaml)
          echo "DEPLOY_COMMAND=$DEPLOY_COMMAND" >> $GITHUB_ENV

      - name: Login gcloud
        id: auth
        if: ${{ env.APP_GROUP == env.TESSELL_GCP_APP_NAME }}
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.TESSELL_GCP_SERVICE_ACCOUNT_KEY_JSON }}'
          token_format: access_token
          create_credentials_file: true

      - name: Execute Deployment Script
        if: ${{ env.DEPLOY_COMMAND != null }}
        run: |
          echo ${DEPLOY_COMMAND}
          ${DEPLOY_COMMAND}
