---
name: Check Changed Files

on:
  workflow_call:
    inputs:
      changed-files:
        description: 'All the changed files in PR'
        required: true
        type: string
    outputs:
      required-teams:
        description: 'Teams required for approval'
        value: ${{ jobs.read-codeowners.outputs.required-teams }}

jobs:
  
  read-codeowners:
    runs-on: non-build
    env:
      CI-BRANCH: TDEVOPS-1832
      OWNER: "${{github.repository_owner}}"
    outputs:
      required-teams: ${{steps.extract-teams.outputs.teams}}
    steps: 
      - uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
          ref: ${{github.base_ref}}

      - name: Setup CI Scripts
        run: |
          cd ~/convoy-ci
          git checkout ${{env.CI-BRANCH}}
          git pull
          cd ~-
          cp -r ~/convoy-ci/.github/scripts ./scripts
 
      - name: Extract team names from CODEOWNERS
        id: extract-teams
        env:
          changed-files: "${{ inputs.changed-files }}"
        run: |
          python3 ./scripts/python/read_codeowners.py