---
name: Master CI Merge Workflows
on:
  workflow_call:
    
jobs:

  file-check:
    uses: TessellDevelopment/convoy-ci/.github/workflows/master_file_check.yml@main
    secrets: inherit

  runner-check:
    runs-on: non-build
    needs: file-check
    outputs:
      type: ${{steps.runner-type.outputs.type}}
      label: ${{steps.get-label.outputs.label}}
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
          
      - name: Get Label
        id: get-label
        shell: bash
        run: |
          if [ -f convoy.yaml ]; then
            if [[ "${{ github.event.pull_request.base.ref }}" == "main" ]]; then
              APP_GROUP=$(yq '.appGroup // "tessell"' convoy.yaml)
              URL="http://${{vars.CONVOY_API_ENDPOINT}}/devops/applications/app-groups/$APP_GROUP/latest-main-release-label"
              RESPONSE=$(curl -f --location "$URL" --header "x-api-key: ${{secrets.CONVOY_AUTH_TOKEN}}")
              echo "$RESPONSE"
              LABEL=$(echo "$RESPONSE" | jq -r '.["latest-main-release-label"]')
              echo "$LABEL"
              if [[ $LABEL == rel-* ]]; then
                  echo "LABEL=$LABEL" >> $GITHUB_OUTPUT
              else
                  echo "Response: $LABEL"
                  echo "Label does not start with 'rel'. Check response."
                  exit 1 
              fi
            else
              echo "LABEL=${{ github.event.pull_request.base.ref }}" >> $GITHUB_OUTPUT
            fi
           else
            echo "convoy.yaml not found"
           fi 
          
      - name: Determine runner type from Convoy
        id: runner-type
        run: |
          runner=$(yq '.runner' convoy.yaml)
          echo "type=$runner" >> $GITHUB_OUTPUT
  
  create-tag:
    needs: runner-check
    uses: TessellDevelopment/convoy-ci/.github/workflows/master_create_tag.yml@main
    secrets: inherit
    with:
      label: ${{needs.runner-check.outputs.label}}

  post-tag-to-convoy:
    if: needs.file-check.outputs.github-changes == 'false'
    needs: create-tag
    uses: TessellDevelopment/convoy-ci/.github/workflows/master_post_tag_convoy.yml@main
    secrets: inherit
    with:
      tag: ${{needs.create-tag.outputs.tag}}
      uses_custom_version: ${{needs.create-tag.outputs.uses_custom_version}}

  find-latest-tag:
    if: needs.file-check.outputs.github-changes == 'false'
    needs: create-tag
    uses: TessellDevelopment/convoy-ci/.github/workflows/master_find_latest_tag.yml@main
    secrets: inherit

  build:
    needs: [runner-check,find-latest-tag]
    uses: TessellDevelopment/convoy-ci/.github/workflows/master_build_merge.yml@TDEVOPS-1982
    secrets: inherit
    with:
      type: ${{needs.runner-check.outputs.type}}
      tag: ${{needs.find-latest-tag.outputs.tag}}
      label: ${{needs.runner-check.outputs.label}}

  post-build-to-convoy:
    if: ${{needs.file-check.outputs.github-changes == 'false' && always()}}
    needs: build
    uses: TessellDevelopment/convoy-ci/.github/workflows/master_post_build_convoy.yml@main
    secrets: inherit

  create-double-commit:
    if: startsWith(github.event.pull_request.base.ref, 'rel')
    needs: create-tag
    uses: TessellDevelopment/convoy-ci/.github/workflows/master_create_double_commit.yml@main
    secrets: inherit

  send-mail:
    needs: create-double-commit
    if: failure() && (contains(github.event.pull_request.head.ref, 'double_commit'))
    uses: TessellDevelopment/convoy-ci/.github/workflows/master_send_email.yml@main 
    secrets: inherit
