---
name: Check Required Approvals
on:
  workflow_call:
    inputs:
      required-teams:
        description: 'Teams required for approval in the PR'
        required: true
        type: string
 
jobs:

  check-approval:
    runs-on: non-build
    env:
      CI-BRANCH: TDEVOPS-1832
      GITHUB_TOKEN: ${{ secrets.CIPIPELINE_GITHUB_TOKEN }}
      GH_API_URL: ${{vars.GH_API_URL}}
      OWNER: ${{github.repository_owner}}
      PR_NUMBER: ${{ github.event.pull_request.number }}
      PR_TITLE: ${{github.event.pull_request.head.ref}}
      REPO: ${{ github.repository }}
      TEAMS: ${{inputs.required-teams}}
      USER: ${{github.event.pull_request.user.login}}
    steps:
        - uses: actions/checkout@v4.1.1
          with:
            fetch-depth: 0

        - name: Setup CI Scripts
          run: |
            cd ~/convoy-ci
            git checkout ${{env.CI-BRANCH}}
            git pull
            cd ~-
            cp -r ~/convoy-ci/.github/ci-scripts ./ci-scripts

        - name: Check Approval
          run: |
            bash ./ci-scripts/bash/check_approval.sh check_approval
