---
name: Publish Signed Windows Artifacts
on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
      label:
        required: true
        type: string

jobs:
  publish-signed-artifacts:
    runs-on: self-hosted
    env:
      ARTIFACTS_DEV_ACCESS_KEY: ${{ secrets.ARTIFACTS_DEV_ACCESS_KEY }}
      ARTIFACTS_DEV_SECRET_KEY: ${{ secrets.ARTIFACTS_DEV_SECRET_KEY }}
      ARTIFACTS_DEV_S3: ${{vars.ARTIFACTS_DEV_S3}}
      LATEST_TAG: ${{ inputs.tag }}
      LABEL: ${{ inputs.label }}
      CI_BRANCH: TDEVOPS-3868_win_ci


      ARTIFACTS_UPLOAD_ACCESS_KEY: ${{ secrets.ARTIFACTS_UPLOAD_ACCESS_KEY }}
      ARTIFACTS_UPLOAD_SECRET_KEY: ${{ secrets.ARTIFACTS_UPLOAD_SECRET_KEY }}
      AWS_ACCOUNT_CODE_COVERAGE: ${{vars.AWS_ACCOUNT_CODE_COVERAGE}}
      AWS_ACCOUNT_TESSELL_COMMON_INFRA: ${{vars.AWS_ACCOUNT_TESSELL_COMMON_INFRA}}
      AWS_ACCOUNT_TESSELL_DEV: ${{vars.AWS_ACCOUNT_TESSELL_DEV}}
      AWS_ACCOUNT_TESSELL_DEVOPS: ${{vars.AWS_ACCOUNT_TESSELL_DEVOPS}}
      AWS_ACCOUNT_TESSELL_QA: ${{vars.AWS_ACCOUNT_TESSELL_QA}}
      AWS_ACCOUNT_TESSELL_STAGE: ${{vars.AWS_ACCOUNT_TESSELL_STAGE}}
      AWS_ACCOUNT_TESSELL_PROD: ${{vars.AWS_ACCOUNT_TESSELL_PROD}}
      BASE_BRANCH: "${{github.event.pull_request.base.ref}}"
      BRANCH_NAME: ${{ github.event.pull_request.head.ref }}
      CI_PHASE: postMerge
      CITEST_APP_NAME: ${{vars.CITEST_APP_NAME}}
      CODE_COVERAGE_S3: ${{vars.CODE_COVERAGE_S3}}
      CONTENT_FOR_GITHUB_OUTPUT: /tmp/content-for-github-output
      CONVOY_API_KEY: ${{secrets.CONVOY_AUTH_TOKEN}}
      DEV_BUILD: ${{inputs.dev_build}}
      DEVOPS_GIT_METADATA_API_ENDPOINT: http://${{vars.CONVOY_DEV_API_ENDPOINT}}/devops/git-metadata
      DEVQA_INFRA_ACCESS_KEY: ${{ secrets.DEVQA_INFRA_ACCESS_KEY }}
      DEVQA_INFRA_SECRET_KEY: ${{ secrets.DEVQA_INFRA_SECRET_KEY }}
      DISPATCH_BRANCH_NAME: ${{ github.ref_name }}
      DOCKERHUB_ORG: ${{vars.DOCKERHUB_ORG}}
      DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
      GIT_BASE_REF: ${{ github.event.pull_request.base.sha != '' && github.event.pull_request.base.sha || (inputs.dev_build && inputs.GIT_BASE_REF || '') }}
      GITHUB_TOKEN: ${{ secrets.CIPIPELINE_GITHUB_TOKEN }}
      GITHUB_USER: ${{ secrets.CIPIPELINE_GITHUB_USER }}
      GH_API_URL: ${{vars.GH_API_URL}}
      GOPATH: /home/github/go
      IMAGE_SCAN_API_URL: http://${{vars.CONVOY_DEV_API_ENDPOINT}}/devops/code/vulnerabilities/validate
      NAMESPACE: "convoy"
      NEXUS_ADDR: http://nexus.nexus.svc.cluster.local
      NEXUS_PASSWORD: ${{secrets.CIPIPELINE_NEXUS_PASSWORD}}
      NEXUS_PROTOCOL: ${{vars.NEXUS_PROTOCOL_LOCAL}}
      NEXUS_PULL_REPOS_M2: tessell-m2-component
      NEXUS_PULL_REPOS_PY: tessell-py-component
      NEXUS_PUSH_REPOS_M2: ${{ vars.NEXUS_PUSH_REPOS_M2 }}
      NEXUS_PUSH_REPOS_PY: ${{ vars.NEXUS_PUSH_REPOS_PY }}
      NEXUS_SERVER_ENDPOINT: ${{vars.NEXUS_SERVER_ENDPOINT_LOCAL}}
      NEXUS_USERNAME: ${{secrets.CIPIPELINE_NEXUS_USERNAME}}
      PACKER_AWS_ACCESS_KEY_ID: ${{ secrets.PACKER_AWS_ACCESS_KEY_ID }}
      PACKER_AWS_SECRET_ACCESS_KEY: ${{ secrets.PACKER_AWS_SECRET_ACCESS_KEY }}
      PACKER_AZURE_CLIENT_ID: ${{ secrets.PACKER_AZURE_CLIENT_ID }}
      PACKER_AZURE_CLIENT_SECRET: ${{ secrets.PACKER_AZURE_CLIENT_SECRET }}
      PACKER_AZURE_TENANT_ID: ${{ secrets.PACKER_AZURE_TENANT_ID }}
      PACKER_AZURE_SUBSCRIPTION_ID: ${{ secrets.PACKER_AZURE_SUBSCRIPTION_ID }}
      PROD_ASSET_ACCESS_KEY: ${{ secrets.PROD_ASSET_ACCESS_KEY }}
      PROD_ASSET_SECRET_KEY: ${{ secrets.PROD_ASSET_SECRET_KEY }}
      PR_NUMBER: ${{ github.event.pull_request.number }}
      RELEASE_PATH: ${{inputs.label}}
      REPO: "${{github.event.pull_request.base.repo.name}}"
      REPOSITORY: "${{github.repository}}"
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      TESSELLTOOLS_S3: ${{vars.TESSELL_ARTIFACTS_PROD_ASSETS_S3}}
      TESSELL_APP_NAME: ${{vars.TESSELL_APP_NAME}}
      TESSELL_TERRAFORM_MODULES_TERLS_S3: ${{vars.TESSELL_ARTIFACTS_TF_DEV_S3}}
      TESSELL_TERRAFORM_MODULES_BARC_S3: ${{vars.TESSELL_ARTIFACTS_TF_QA_S3}}
      TESSELL_TERRAFORM_MODULES_STAGE_S3: ${{vars.TESSELL_ARTIFACTS_TF_STAGE_S3}}
      TESSELL_TERRAFORM_MODULES_BETA_S3: ${{vars.TESSELL_ARTIFACTS_TF_PROD_S3}}
      TESSELL_GCP_APP_NAME: ${{ vars.TESSELL_GCP_APP_NAME }}
      TESSELL_GCP_ARTIFACTS_BUCKET: ${{ vars.TESSELL_GCP_ARTIFACTS_BUCKET }}
      TESSELL_GCP_DOCKERHUB_ORG: ${{vars.TESSELL_GCP_DOCKERHUB_ORG}}
      TESSELL_GCP_PROJECT_ID: ${{vars.TESSELL_GCP_PROJECT_ID}}
      TESSELL_GCP_REGION: ${{vars.TESSELL_GCP_REGION}}
      TESSELL_GCP_SERVICE_ACCOUNT_NAME: ${{vars.TESSELL_GCP_SERVICE_ACCOUNT_NAME}}
      TESSELL_WIN_SQL_DB_USERNAME: ${{ secrets.TESSELL_WIN_SQL_DB_USERNAME }}
      TESSELL_WIN_SQL_DB_PASSWORD: ${{ secrets.TESSELL_WIN_SQL_DB_PASSWORD }}
      TESSELLOPS_APP_NAME: ${{vars.TESSELLOPS_APP_NAME}}
      TS_API_KEY: ${{ secrets.TS_API_KEY }}
      TS_TAILNET: ${{ secrets.TS_TAILNET }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup CI Scripts
        run: |
          cd ~/convoy-ci
          git checkout main
          git pull
          git checkout ${{env.CI_BRANCH}}
          git pull
          cd ~-
          cp -r ~/convoy-ci/.github/ci-scripts ./ci-scripts

      - name: Download signed artifacts
        uses: actions/download-artifact@v4
        with:
          name: signed-windows-artifacts
          path: signed

      - name: Publish signed artifacts
        run: |
          set +e
          echo "CI_BRANCH=${{env.CI_BRANCH}}"
          echo "source ./ci-scripts/bash/functions-for-build"
          source ./ci-scripts/bash/functions-for-build
          APP_GROUP=$(yq '.appGroup // "tessell"' convoy.yaml)

          for tarFile in signed/*.tar; do
            ARTIFACT=$(basename "$tarFile" .tar)
            
            if [[ $APP_GROUP == $TESSELL_GCP_APP_NAME ]]; then
              push_to_gcloud "$tarFile" "gs://${TESSELL_GCP_ARTIFACTS_BUCKET}/${LABEL}/${ARTIFACT}/${ARTIFACT}-${LATEST_TAG}.tar"
              generate_checksum "$ARTIFACT.tar"
            else
              mvnDeploy "$ARTIFACT" "tar" "$tarFile" "${APP_GROUP}.agent" "${LATEST_TAG}"
              awsConfigureProdAssets
              push_release_manifest_artifacts "$(basename $tarFile)" "$tarFile"
            fi
          done

      - name: Slack Notification
        uses: act10ns/slack@v2.0.0
        if: failure()
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          channel: ${{ secrets.SLACK_DEVOPS_CHANNEL }}
