---
name: Build Status POST API to Convoy
on:
  workflow_call:
    inputs:
      IS_ANY_ARTIFACT_GENERATED: 
        description: 'Flag if any artifact was pushed during build'
        required: true
        default: "true"
        type: string
      ARTIFACT_CHECKSUMS:
        description: 'Consolidated Checksum of generated artifacts'
        default: ""
        type: string
      TAG:
        description: 'Tag created during create-tag'
        required: true
        type: string
      LABEL:
        description: 'Release label for upload'
        required: true
        type: string
      IS_CONTENT_FOR_GITHUB_OUTPUT_POPULATED:
        description: Bool flag to determine whether the GitHub artifact CONTENT_FOR_GITHUB_OUTPUT has been populated
        default: "false"
        type: string

jobs:
  
  post-build-status-to-convoy:
    runs-on: non-build
    env: 
      SLACK_WEBHOOK_URL: ${{ secrets.CONVOY_ALERTS_SLACK_URL }}
      TAG: "${{inputs.TAG}}"
      LABEL: "${{inputs.LABEL}}"
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0

      - name: Get branch name
        shell: bash
        run: |
          echo "SOURCE_BRANCH=$(echo ${GITHUB_REF#refs/heads/} | tr / -)" >> $GITHUB_ENV

      # - name: Check specific file changes
      #   if: endsWith(github.event.pull_request.base.repo.name, 'helm-svc-defns')
      #   id: helm-files
      #   uses: tj-actions/changed-files@v42.0.2
      #   with:
      #     files: |
      #       Chart.yaml
      #       services/**

      - uses: technote-space/workflow-conclusion-action@v3.0.3
        if: ${{ startsWith(env.SOURCE_BRANCH,'rel-') || env.SOURCE_BRANCH == 'main' }}
        with:
          GITHUB_TOKEN: ${{ secrets.CIPIPELINE_GITHUB_TOKEN }}

      - name: Download generated artifacts file
        uses: actions/download-artifact@v4
        if: ${{ inputs.IS_CONTENT_FOR_GITHUB_OUTPUT_POPULATED == 'true' }}
        with:
          name: generated-artifacts
          path: /tmp

      - name: POST API to Convoy
        env:
          API_URL: http://${{vars.CONVOY_API_ENDPOINT}}/devops/git-metadata/build-status
          API_URL_REPLICATE: http://${{vars.CONVOY_API_ENDPOINT}}/devops/applications/replicate-artifacts
          API_KEY: ${{secrets.CONVOY_AUTH_TOKEN}}
          GH_API_URL: ${{vars.GH_API_URL}}
          ARTIFACT_CHECKSUMS: ${{inputs.ARTIFACT_CHECKSUMS}}
          CONTENT_FOR_GITHUB_OUTPUT: /tmp/content-for-github-output
          COMMIT_HASH: "${{github.sha}}"
          IS_CONTENT_FOR_GITHUB_OUTPUT_POPULATED: ${{inputs.IS_CONTENT_FOR_GITHUB_OUTPUT_POPULATED}}
          IS_ANY_ARTIFACT_GENERATED: ${{inputs.IS_ANY_ARTIFACT_GENERATED}}
          REPO: "${{github.event.pull_request.base.repo.name}}"
          BASE_BRANCH: "${{github.event.pull_request.base.ref}}"
          GITHUB_TOKEN: ${{ secrets.CIPIPELINE_GITHUB_TOKEN }}
          OWNER: ${{github.repository_owner}}
          STATUS: "${{env.WORKFLOW_CONCLUSION}}"
          SOURCE_BRANCH: "${{env.SOURCE_BRANCH}}"
          TAG: "${{env.TAG}}"
          LABEL: "${{env.LABEL}}"
        run: |
            set -a
            [[ ${IS_CONTENT_FOR_GITHUB_OUTPUT_POPULATED} == true ]] && source ${CONTENT_FOR_GITHUB_OUTPUT}
            set +a
            python3 .github/ci-scripts/python/post_build_convoy.py

      - name: Slack Notification
        uses: act10ns/slack@v2.0.0
        with:
            status: ${{ job.status }}
            steps: ${{ toJson(steps) }}
            channel: ${{ secrets.CONVOY_ALERTS_SLACK_CHANNEL  }}
        if: failure()
