---
name: Tessell Pipelines Code Build Pre Merge
on:
  workflow_call:
    inputs:
      type:
        description: 'This is used to determine build type'
        required: true
        type: string

jobs:

  build-amd:
    if: ${{inputs.type != 'GRAALVM' }}
    runs-on: amd64
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL  }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
  
  build-arm:
    if: ${{inputs.type == 'GRAALVM' }}
    runs-on: ARM64
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL  }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build OPS
        run: |
          sudo ./mvnw install -Dnative -DskipTests -Dquarkus.native.container-build=true
          echo "Build successful"
          if [ "${{github.repository}}" = "TessellDevelopment/tessellops-tsproxy-service" ]; then
            docker build -f src/main/docker/Dockerfile.tailscale -t tsproxy .
          fi
          sudo rm -rf target

      - name: Remove in case of failure
        if: failure()
        run: |
          sudo rm -rf target
          