---
name: Tessell Pipelines Code Build Pre Merge
on:
  workflow_call:
    inputs:
      type:
        description: 'This is used to determine build type'
        required: true
        type: string

env:
  CI_BRANCH: main
  CHANNEL_ID: ${{vars.CONVOY_ALERTS_SLACK_ID}}
  CODE_COVERAGE_S3: ${{vars.CODE_COVERAGE_S3}}
  CONVOY_API_KEY: ${{secrets.CONVOY_AUTH_TOKEN}}
  DEVOPS_TEAM: ${{vars.DEVOPS_TEAM_SLACK_ID}}
  DOCKERHUB_ORG: ${{vars.DOCKERHUB_ORG}}
  GITHUB_TOKEN: ${{ secrets.CIPIPELINE_GITHUB_TOKEN }}
  GITHUB_USER: ${{ secrets.CIPIPELINE_GITHUB_USER }}
  NEXUS_PASSWORD: ${{secrets.CIPIPELINE_NEXUS_PASSWORD}}
  NEXUS_PULL_REPOS_M2: tessell-m2-development
  NEXUS_PULL_REPOS_PY: tessell-py-development
  NEXUS_PUSH_REPOS_M2: ${{ vars.NEXUS_PUSH_REPOS_M2 }}
  NEXUS_PUSH_REPOS_PY: ${{ vars.NEXUS_PUSH_REPOS_PY }}
  NEXUS_PUSH_REPOS_NPM: ${{vars.NEXUS_PUSH_REPOS_NPM}}
  NEXUS_REPO_NPM: tessell-repos-npm-development
  NEXUS_USERNAME: ${{secrets.CIPIPELINE_NEXUS_USERNAME}}
  REPO: "${{github.repository}}"
  REPOS_EXCLUDED_FROM_TRIVY_SCAN: ${{vars.REPOS_EXCLUDED_FROM_TRIVY_SCAN}}
  SLACK_TOKEN: ${{secrets.SLACK_TOKEN}}
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

jobs:

  build-ui:
    if: ${{ inputs.type == 'ui-build' }}
    runs-on: ui-build
    env:
      IMAGE_SCAN_API_URL: http://${{vars.CONVOY_API_ENDPOINT}}/devops/code/vulnerabilities/validate
      NEXUS_PROTOCOL: ${{vars.NEXUS_PROTOCOL_PUBLIC}}
      NEXUS_SERVER_ENDPOINT: ${{vars.NEXUS_SERVER_ENDPOINT_PUBLIC}}
      TESSELL_UI_ENV_SECRET: "${{secrets.TESSELL_UI_ENV_SECRET}}"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0

      - name: Setup CI Scripts
        run: |
          cd ~/convoy-ci
          git checkout main
          git pull
          git checkout ${{env.CI_BRANCH}}
          git pull
          cd ~-
          cp -r ~/convoy-ci/.github/ci-scripts ./ci-scripts

      - name: Build
        shell: bash
        run: |
          build() {
            type="$1"
            check=$(grep "$type" convoy.yaml)
            if [[ -z "$check" ]]; then
              return
            fi
            version=$(yq '.version' convoy.yaml)
            yq e ".generates.$type[] | [.name, .buildFunction, .extension, .dockerFile] | @csv" convoy.yaml | sed 's/,/ /g' > artifacts.txt
            lineNumber=1
            while :; do
              echo ------------------------------
              artifactData=$(sed "$lineNumber!d" artifacts.txt)
              if [[ -z "$artifactData" ]]; then
                break
              fi
              read -r name buildFunction ext file <<< "$artifactData"
              echo "Name: $name"
              echo "buildFunction: $buildFunction"
              echo "Ext: $ext"
              echo "Version: $version"
              echo "dockerFile: $file"
              $buildFunction $name $ext $version $file 
              echo "$type $name done"
              echo ------------------------------
              lineNumber=$((lineNumber+1))
            done
            rm artifacts.txt
          }
          set +e
          source ./ci-scripts/bash/functions-for-build
          build "artifacts"
          build "dockerImages"
          build "helmCharts"
          parseCoverageReport
  
  build-ubuntu-latest:
    if: ${{ inputs.type == 'ubuntu-latest' }}
    runs-on: ubuntu-latest
    env:
      IMAGE_SCAN_API_URL: http://${{vars.CONVOY_PUBLIC_API_ENDPOINT}}/devops/code/vulnerabilities/validate
      NEXUS_PROTOCOL: ${{vars.NEXUS_PROTOCOL_PUBLIC}}
      NEXUS_SERVER_ENDPOINT: ${{vars.NEXUS_SERVER_ENDPOINT_PUBLIC}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5.0.0
        with:
          python-version: 3.9

      - name: Setup Go
        uses: actions/setup-go@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v4.0.0
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3.0.0

      - name: Login to docker
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Setup CI Scripts
        run: |
          git clone https://${GITHUB_USER}:${GITHUB_TOKEN}@github.com/TessellDevelopment/convoy-ci.git
          cd convoy-ci
          git checkout ${{env.CI_BRANCH}}
          git pull
          cd ..
          cp -r ./convoy-ci/.github/ci-scripts ./ci-scripts

      - name: Create pip conf
        shell: bash
        run: |
          source ./ci-scripts/bash/functions-for-build
          createPipConf

      - name: Install dependencies
        run: |
          source ./ci-scripts/bash/functions-for-build
          installPythonDependencies

      - name: Setup Trivy and Dockle
        run: |
          source ./ci-scripts/bash/functions-for-build
          setupTrivyDockle

      - name: Build
        shell: bash
        run: |
          build() {
            type="$1"
            check=$(grep "$type" convoy.yaml)
            if [[ -z "$check" ]]; then
              return
            fi
            version=$(yq '.version' convoy.yaml)
            yq e ".generates.$type[] | [.name, .buildFunction, .extension, .dockerFile, .filePath, .baseImage] | @csv" convoy.yaml | sed 's/,/ /g' > artifacts.txt
            lineNumber=1
            while :; do
              echo ------------------------------
              artifactData=$(sed "$lineNumber!d" artifacts.txt)
              if [[ -z "$artifactData" ]]; then
                break
              fi
              read -r name buildFunction ext file filePath baseImage <<< "$artifactData"
              echo "Name: $name"
              echo "buildFunction: $buildFunction"
              echo "Ext: $ext"
              echo "Version: $version"
              echo "dockerFile: $file"
              echo "filePath: $filePath"
              echo "baseImage: $baseImage"
              $buildFunction "$name" "$ext" "$version" "$file" "$filePath" "$baseImage"
              echo "$type $name done"
              echo ------------------------------
              lineNumber=$((lineNumber+1))
            done
            rm artifacts.txt
          }
          set +e
          source ./ci-scripts/bash/functions-for-build
          build "artifacts"
          build "dockerImages"
          build "helmCharts"
          parseCoverageReport

  build-amd:
    if: ${{ inputs.type == 'amd' }}
    runs-on: self-hosted
    env:
      ARTIFACTS_UPLOAD_ACCESS_KEY: ${{ secrets.ARTIFACTS_UPLOAD_ACCESS_KEY }}
      ARTIFACTS_UPLOAD_SECRET_KEY: ${{ secrets.ARTIFACTS_UPLOAD_SECRET_KEY }}
      AWS_ACCOUNT_TESSELL_COMMON_INFRA: ${{vars.AWS_ACCOUNT_TESSELL_COMMON_INFRA}}
      AWS_ACCOUNT_TESSELL_DEVOPS: ${{vars.AWS_ACCOUNT_TESSELL_DEVOPS}}
      BASE_BRANCH: ${{ github.event.pull_request.base.ref }}
      BRANCH_NAME: ${{ github.event.pull_request.head.ref }}
      CI_PHASE: preMerge
      DEVOPS_GIT_METADATA_API_ENDPOINT: http://${{vars.CONVOY_API_ENDPOINT}}/devops/git-metadata
      DEVQA_INFRA_ACCESS_KEY: ${{ secrets.DEVQA_INFRA_ACCESS_KEY }}
      DEVQA_INFRA_SECRET_KEY: ${{ secrets.DEVQA_INFRA_SECRET_KEY }}
      DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
      GIT_BASE_REF: ${{ github.event.pull_request.base.sha }}
      GITHUB_BASE_REF: ${{ github.base_ref }}
      GH_API_URL: ${{vars.GH_API_URL}}
      GOPATH: /home/github/go
      IMAGE_SCAN_API_URL: http://${{vars.CONVOY_API_ENDPOINT}}/devops/code/vulnerabilities/validate
      NAMESPACE: "convoy"
      NEXUS_PROTOCOL: ${{vars.NEXUS_PROTOCOL_LOCAL}}
      NEXUS_SERVER_ENDPOINT: ${{vars.NEXUS_SERVER_ENDPOINT_LOCAL}}
      PACKER_AWS_ACCESS_KEY_ID: ${{ secrets.PACKER_AWS_ACCESS_KEY_ID }}
      PACKER_AWS_SECRET_ACCESS_KEY: ${{ secrets.PACKER_AWS_SECRET_ACCESS_KEY }}
      PACKER_AZURE_CLIENT_ID: ${{ secrets.PACKER_AZURE_CLIENT_ID }}
      PACKER_AZURE_CLIENT_SECRET: ${{ secrets.PACKER_AZURE_CLIENT_SECRET }}
      PACKER_AZURE_TENANT_ID: ${{ secrets.PACKER_AZURE_TENANT_ID }}
      PACKER_AZURE_SUBSCRIPTION_ID: ${{ secrets.PACKER_AZURE_SUBSCRIPTION_ID }}
      PR_NUMBER: ${{ github.event.pull_request.number }}
      REPOSITORY: "${{github.repository}}"
      SOURCE_BRANCH: ${{ github.head_ref }}
      TS_API_KEY: ${{ secrets.TS_API_KEY }}
      TS_TAILNET: ${{ secrets.TS_TAILNET }}
      TESSELL_WIN_SQL_DB_USERNAME: ${{ secrets.TESSELL_WIN_SQL_DB_USERNAME }}
      TESSELL_WIN_SQL_DB_PASSWORD: ${{ secrets.TESSELL_WIN_SQL_DB_PASSWORD }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0

      - name: Setup CI Scripts
        run: |
          cd ~/convoy-ci
          git checkout main
          git pull
          git checkout ${{env.CI_BRANCH}}
          git pull
          cd ~-
          cp -r ~/convoy-ci/.github/ci-scripts ./ci-scripts

      - name: Check All file changes
        id: changed-files-all
        uses: step-security/changed-files@v45.0.1

      - name: Login gcloud
        id: auth
        if: ${{ contains(env.REPOSITORY, 'tessell-software-library-image-defns')  }}
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.TESSELL_GCP_SERVICE_ACCOUNT_KEY_JSON }}'
          token_format: access_token
          create_credentials_file: true

      - name: Login to docker
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build
        shell: bash
        run: |
          build() {
            type="$1"
            git config --global url."https://${GITHUB_USER}:${GITHUB_TOKEN}@github.com".insteadOf "https://github.com"
            version=$(yq '.version // ""' convoy.yaml)
            language=$(yq '.language // ""' convoy.yaml)
            echo "Building ${type}"
            if [[ "$language" == "terraform" ]]; then
              terraformBuild
              return
            fi
            check=$(yq ".generates.${type} // \"\"" convoy.yaml)
            if [[ -z "$check" ]]; then
              echo "Skipping build for ${type}"
              return
            fi
            yq e ".generates.$type[] | [.name, .buildFunction, .buildTool, .extension, .dockerFile] | @csv" convoy.yaml | sed 's/null//g' > artifacts.txt
            lineNumber=1
            while :; do
              echo ------------------------------
              artifactData=$(sed "${lineNumber}!d" artifacts.txt)
              if [[ -z "${artifactData}" ]]; then
                break
              fi

              set -x
              java_version=$(yq '.javaVersion // ""' convoy.yaml)
              if [[ -n ${java_version:-} ]]; then
                if [[ -d /usr/lib/jvm/java-${java_version}-openjdk-amd64 ]]; then
                  export JAVA_HOME=/usr/lib/jvm/java-${java_version}-openjdk-amd64
                  export PATH="/usr/lib/jvm/java-${java_version}-openjdk-amd64/bin:${PATH}"
                else
                  echo "Java Version ${java_version}, as required in convoy.yaml, is not installed"
                  exit 1
                fi
              fi

              IFS=',' read -r name buildFunction buildTool ext file <<< "${artifactData}"
              export ARTIFACT_NAME=${name} ARTIFACT_EXTENSION=${ext} ARTIFACT_VERSION=${version} DOCKERFILE_PATH=${file}
              echo "Name: ${name}"
              echo "buildFunction: ${buildFunction}"
              echo "buildTool: ${buildTool}"
              echo "Ext: ${ext}"
              echo "Version: ${version}"
              echo "dockerFile: ${file}"

              if [[ -n ${buildFunction:-} ]]; then
                ${buildFunction} ${name} ${ext} ${version} ${file}
              elif [[ -n ${buildTool:-} ]]; then
                set -e
                $(yq .pre-merge.${buildTool} ./ci-scripts/bash/build-tool-cmd-map.yaml)
                set +e
              fi
              set +x

              echo "$type $name done"
              echo ------------------------------
              lineNumber=$((lineNumber+1))
            done
            rm artifacts.txt
          }
          set +e
          source ./ci-scripts/bash/functions-for-build
          [[ -n ${LATEST_TAG:-} ]] || export LATEST_TAG=0.0.0
          configureGoVersionIfRequired
          set -e; bash -c "$(yq ".ci.${CI_PHASE}.cmd // \"\"" convoy.yaml)"; set +e
          build "artifacts"
          build "dockerImages"
          build "helmCharts"
          build "terraform"
          parseCoverageReport

      - name: Cleanup
        if: always()
        run: |
          set +e
          sudo rm -rf target
          docker container prune --force
          docker volume prune --force

  build-arm:
    if: ${{ inputs.type == 'arm' }}
    runs-on: ARM64
    env:
      IMAGE_SCAN_API_URL: http://${{vars.CONVOY_API_ENDPOINT}}/devops/code/vulnerabilities/validate
      NEXUS_PROTOCOL: ${{vars.NEXUS_PROTOCOL_LOCAL}}
      NEXUS_SERVER_ENDPOINT: ${{vars.NEXUS_SERVER_ENDPOINT_LOCAL}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0

      - name: Setup CI Scripts
        run: |
          cd ~/convoy-ci
          git checkout main
          git pull
          git checkout ${{env.CI_BRANCH}}
          git pull
          cd ~-
          cp -r ~/convoy-ci/.github/ci-scripts ./ci-scripts

      - name: Build
        shell: bash
        run: |
          build() {
            type="$1"
            check=$(grep "$type" convoy.yaml)
            if [[ -z "$check" ]]; then
              return
            fi
            version=$(yq '.version' convoy.yaml)
            yq e ".generates.$type[] | [.name, .buildFunction, .extension, .dockerFile] | @csv" convoy.yaml | sed 's/,/ /g' > artifacts.txt
            lineNumber=1
            while :; do
              echo ------------------------------
              artifactData=$(sed "$lineNumber!d" artifacts.txt)
              if [[ -z "$artifactData" ]]; then
                break
              fi
              read -r name buildFunction ext file <<< "$artifactData"
              echo "Name: $name"
              echo "buildFunction: $buildFunction"
              echo "Ext: $ext"
              echo "Version: $version"
              echo "dockerFile: $file"
              $buildFunction $name $ext $version $file 
              echo "$type $name done"
              echo ------------------------------
              lineNumber=$((lineNumber+1))
            done
            rm artifacts.txt
          }
          set +e
          source ./ci-scripts/bash/functions-for-build
          build "artifacts"
          build "dockerImages"
          build "helmCharts"
          parseCoverageReport

      - name: Cleanup
        if: always()
        run: |
          set +e
          sudo rm -rf target
          docker container prune --force
          docker volume prune --force
