---
name: Tessell Pipelines Code Build for PR

on:
  workflow_call:
    inputs:
      type:
        description: 'This is used to determine build type'
        required: true
        type: string

  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL  }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: '11'

      - name: Install Maven
        run: |
          wget -q https://archive.apache.org/dist/maven/maven-3/3.9.4/binaries/apache-maven-3.9.4-bin.tar.gz
          tar xf apache-maven-3.9.4-bin.tar.gz
          export PATH=$PATH:$(pwd)/apache-maven-3.9.4/bin
          mvn -version
          rm apache-maven-3.9.4-bin.tar.gz
        
      - name: Build OPS
        if: ${{inputs.type}} == 'OPS'
        run: |
          pwd
          ls
          ./mvnw install -Dnative -DskipTests -Dquarkus.native.container-build=true
          echo "Build successful"
