---
  name: Best Practices Check
  on:
    workflow_call:
    
  jobs:

    dev-checks:
      runs-on: non-build-test
      env:
        CI-BRANCH: TDEVOPS-1832
        BASE_REF: "${{github.base_ref}}"
        BASE_SHA: ${{ github.event.pull_request.base.sha }}
        GITHUB_EVENT_BEFORE: "${{ github.event.before }}"
        GITHUB_EVENT_NAME: "${{ github.event_name }}"
        GITHUB_SHA: "${{ github.sha }}"
        GITHUB_TOKEN: ${{ secrets.CIPIPELINE_GITHUB_TOKEN }}
        HEAD_BRANCH: ${{ github.event.pull_request.head.ref}}
        HEAD_SHA: ${{ github.event.pull_request.head.sha }}
        JIRA_USERNAME: ${{ secrets.JIRA_USERNAME }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
        OWNER: "${{ github.repository_owner }}"
        PR_TITLE: "${{github.event.pull_request.title}}"
        REPO: "${{  github.repository }}"
        SUPPORTED_JIRA_PROJECTS: "${{vars.SUPPORTED_JIRA_PROJECTS}}" 
        USER: "${{github.event.pull_request.user.login}}"
      steps:
      
        - uses: actions/checkout@v4.1.1
          with:
            fetch-depth: 0

        - name: Dump GitHub context
          env:
            GITHUB_CONTEXT: ${{ toJson(github) }}
          run: |
            echo "$GITHUB_CONTEXT"

        - name: Setup CI Scripts
          run: |
            cd ~/convoy-ci
            git checkout ${{env.CI-BRANCH}}
            git pull
            cd ~-
            cp -r ~/convoy-ci/.github/scripts ./scripts
        
        - name: Check Format
          run: |
            bash ./scripts/bash/check_jira_format.sh
              
        - name: Validate Jira Ticket
          run: |
            if echo "${{ env.HEAD_BRANCH }}" | grep -Eq '^revert-'; then
                echo "Revert branch, skipping Jira Extraction"
                exit 0
            fi
            python3 ./scripts/python/validate_jira_ticket.py

        - name: Check double commit
          run: |
            if ([[ "${{ env.USER }}" != "cipipelinetessell" ]]) && ([[ "$BRANCH" == *"double_commit"* ]] || [[ "$PR_TITLE" == *"Double Commit"* ]]); then
              if ([[ "$BRANCH" == *"revert"* ]] && [[ "$PR_TITLE" == *"Revert"* ]]); then
                echo "Revert Double commit Branch. Allowed"
              else   
                echo "Exclude Double commit naming in Branch, PR title and try again."
                exit 1
              fi
            else
              echo "No double commit conflicts found in Branch or PR title."
            fi

        - name: Check for Jsonlint
          run: |
            set -e
            git diff --name-only --diff-filter=AM ${{ env.BASE_SHA }}...${{ env.HEAD_SHA }} | grep '\.json$' | xargs -I{} sh -c 'jsonlint -q "{}" || { echo "::error::Invalid JSON file: {}"; exit 1; }'

        - name: Output PR diff 
          run: |
            node ./scripts/javascript/index.js outputPRDiff

        - name: Check for merge conflicts
          run: |
            node ./scripts/javascript/index.js checkMergeConflicts
              
        - name: Check DB Migration Scripts
          run: |
            node ./scripts/javascript/index.js checkDBMigrationScripts
            
        - name: Run API-spec Validation
          run: |
            if [ -f ".github/scripts/duplicate_check_for_component_paths.py" ]; then
              set -e
              python3 .github/scripts/duplicate_check_for_component_paths.py
            else
              echo "Validation file not present. Skipping check."
            fi
            
        - name: check for terraform (code)
          id: terraform_check
          run: |
            node ./scripts/javascript/index.js checkTerraformVersion
       
        - name: check for terraform version
          if: steps.terraform_check.outputs.terraform_files 
          env:
            terraform_files: ${{ steps.terraform_check.outputs.terraform_files }}
          run: |
            python3 - <<EOF
            import os
            import hcl2
            terraform_files = os.environ.get('terraform_files')
            version_missing = False
            for terraform_file in terraform_files.split(','):
                with open(terraform_file, 'r') as file:
                    tf_file = hcl2.load(file)
                if 'terraform' in tf_file and 'required_providers' in tf_file['terraform'][0]:
                    providers = tf_file['terraform'][0]['required_providers']
                    for provider in providers:
                        for _provider, provider_info in provider.items():
                            for key  in provider_info:
                                if key == 'version':
                                    break
                            else:
                                print(f"{terraform_file}: version is not present for {_provider} ")
                                version_missing = True
                if version_missing:
                    sys.exit(1)
            EOF
        
  
        - name: Check to verify if same branch exists
          if: ${{ startsWith(env.BASE_REF,'rel-') && !contains(env.HEAD_BRANCH,'double_commit') }}
          run: |
            branch_to_check=${{ env.HEAD_BRANCH }}-main-double_commit
            list_of_branches=($(git branch -r | awk -F '/' '{print $2}'))
            for branch in "${list_of_branches[@]}";do
            if [[ "$branch" == "$branch_to_check" ]];then
              echo "Double commit branch with name $branch already exists, please merge and/or delete the branch ";exit 1;
            fi
            done
              